### ISSUE TITLE
Vjump September

### ISSUE THREAD

**Issue by ClementLouis** [EerieCode/Percy-Alpha-Testing#10]
Zombie Horde:
- [x] Zombie Struggle

Savage Strike:
- [x] SAST-JP009 Tech Genus Screw Serpent / T.G. Screw Serpent
- [x] SAST-JP018 Shiranui no Ikusanori / Shiranui Sensei
- [x] SAST-JP019 Shiranui no Mononobe / Shiranui Spearitualist
- [x] SAST-JP037 Varreload Savage Dragon / Borreload Savage Dragon
- [x] SAST-JP038 Cyberse Quantum Dragon
- [ ] SAST-JP041 Ayakashigami – Shiranui / Shiranui Spiritsaga
- [x] SAST-JP044 Uruwashigami – Shiranui / Shiranui Splendidsaga
- [x] SAST-JP048 Salamangrate Sunlight Wolf / Salamangreat Sunlight Wolf
- [x] SAST-JP050 Tech Genus Trident Launcher / T.G. Trident Launcher
- [x] SAST-JP063 Auka Youreitan – Shiranuigatari / Shiranui Story Saga
- [x] SAST-JP067 Gouyoku de Kinman na Tsubo / Pot of Indulgence
- [ ] SAST-JP074 Shiranuiryuu Saika no Jin / Shiranui Style Skill
- [x] SAST-JP078 Yami no Zousan Koujou / Dark Factory of Increased Production
- [ ] SAST-JP079 Majo no Ichigeki / Witch’s Strike => cannot be implemented

Legendary Duellist:
- [x] DP21-JP001 Harpie Perfumer
- [x] DP21-JP002 Harpie Oracle
- [x] DP21-JP003 Bewitching Mirror
- [ ] DP21-JP005 Elegant Harpie Lady

**Comment by AlphaKretin** [comment]
Borreload is uploaded with 1 effect missing, Eerie has done Quantum and Sunlight Wolf, Shiranui main deck monsters, Storysaga and trap are on lock.

**Comment by EerieCode** [comment]
The Pot and the Factory have also been done
