### ISSUE TITLE
Vjump June [TEST]

### ISSUE THREAD

**Issue by NaimSantos** [EerieCode/Percy-Alpha-Testing#104]
- [x] 101010002 - Marincess Mandarin
- [x] 101010003 - Marincess Crown Tail
- [x] 101010004 - Marincess Blue Tongue
- [x] 101010008 - Hakai Douji Arha
- [x] 101010009 - Hakai Douji Rakia
- [x] 101010010 - Hakaishin no Magatama
- [x] 101010040 - Marincess Crystal Heart
- [x] 101010041 - Marincess Wonder Heart
- [x] 101010042 - Marincess Sea Angel
- [x] 101010043 - Hakaishin Ragia
- [x] 101010044 - Hakaishin Arba
- [x] 101010045 - Hakai Souohshin Raigou
- [x] 101010053 - Marincess Battle Ocean
- [x] 101010054 - The Shackles of Souoh
- [x] 101010055 - Wail of the Hakaishin
- [x] 101010067 - Marincess Snow 
- [x] 101010068 - Marincess Cascade
- [x] 101010069 - Hakai Homily
- [x] 101010070 - Hakai Dual Dirge

## Deck Build Pack Mystic Fighters - Zan-Ki - 10041?XXX
- [x] 100423001 - Zan-Ki Sigma - 斬機シグマ
- [x] 100423002 - Zan-Ki Nabla - 斬機ナブラ
- [x] 100423003 - Zan-Ki Adion - 斬機アディオン
- [x] 100423004 - Zan-Ki Subtra - 斬機サブトラ
- [x] 100423005 - Zan-Ki Multiplier - 斬機マルチプライヤー
- [x] 100423006 - Zan-Ki Divison - 斬機ディヴィジョン
- [x] 100423007 - Flame Zan-Ki Magma - 炎斬機マグマ
- [x] 100423008 - Flame Zan-Ki Final Sigma - 炎斬機ファイナルシグマ
- [x] 100423009 - Cluster Zan-Ki Laplacian - 塊斬機ラプラシアン
- [x] 100423010 - Zan-Ki Equation - 斬機方程式
- [x] 100423011 - Zan-Ki Blade Nayuta - 斬機刀ナユタ
- [x] 100423012 - Zan-Ki Inductive Method - 斬機帰納法
- [x] 100423013 - Zan-Ki Super Factorial - 斬機超階乗

**Comment by AlphaKretin** [comment]
All the marincess except Crystal Heart and Snow are tested
