### ISSUE TITLE
New Card - Cauldron of the Old Man

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#105]
Discord is currently down, so in an attempt to communicate I'm putting a single random Twitter reveal here.
https://twitter.com/YuGiOh_OCG_INFO/status/1143126627980738560
Don't have a translation yet, I'll keep an eye out for HHTurtle on Reddit.

**Comment by AlphaKretin** [comment]
HHTurtle has posted a translation. https://www.reddit.com/r/yugioh/comments/c4mh1a/chim_cauldron_of_the_old_man/erx9gd6?utm_source=share&utm_medium=web2x

> Cauldron of the Old Man
> Continuous Spell
> (1) When this card is activated: Place 1 counter on this card.
> (2) Once per turn, during your Standby Phase: Place 1 counter on this card.<Trigger-like>
> (3) Once per turn: You can activate 1 of these effects;<Ignition-like>
> ● Gain 500 LP for each counter on this card.
> ● Inflict 300 damage to your opponent for each counter on this card.

I can start to script it maybe, but I have to leave for a bus soon-ish.

**Comment by AlphaKretin** [comment]
Actually, never mind, I can't script it - it'll take a lot longer without Bastion.

**Comment by NaimSantos** [comment]
I'm taking it

**Comment by EerieCode** [comment]
Discord isn't working anymore... I can't script it at the moment, I'll leave it to you.

**Comment by NaimSantos** [comment]
[Added](https://github.com/EerieCode/Percy-Alpha-Testing/commit/1e66658cdb50f3a215915cf617fd868eea90eec3)
