### ISSUE TITLE
CHIM Gladiator Beasts [Scripts]

### ISSUE THREAD

**Issue by NaimSantos** [EerieCode/Percy-Alpha-Testing#106]
- [x] - 101010011 - Gladiator Beast Sagittarii
- [x] - 101010012 - Gladiator Beast Atrix
- [x] - 101010013 - Gladiator Beast Vespasius
- [x] - 101010033 - Gladiator Beast Domitianus
- [x] - 101010046 - Test Panther
- [x] - 101010056 - Gladiator Beast Comeback - 再起する剣闘獣
- [x] - 101010057 - United Gladiator Beasts
- [x] - 101010058 - Gladiator Rejection - 剣闘排斥波
- [x] - 101010071 - Mad Gladiator Beasts - 猛進する剣闘獣
- [x] - 101010072 - Gladiator Naumachia - 剣闘海戦

**Comment by NaimSantos** [comment]
Taking Gladiator Beast Saditari

**Comment by AlphaKretin** [comment]
Cybercatman is taking Vesperus and Domitianos, Eerie is taking Test Panther and GB United

**Comment by AlphaKretin** [comment]
Did I get all that right? Didn't miss anything? Then I can take Rush and Comeback

**Comment by EerieCode** [comment]
I think I can do Atrix too, if no one else wants it

**Comment by AlphaKretin** [comment]
So making absolutely triple sure this time, and yes this is a question and if the answer is "no" I expect to be told so, Rejection is free and I'm OK to claim it?

**Comment by EerieCode** [comment]
I'll do Naumachia, if no one else is
