### ISSUE TITLE
CHIM Aromage [Scripts]

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#108]
- [x] 101010017 - Aromage Laurier - アロマージ－ローリエ
- [ ] 101010018 - Aromage Marjoram - アロマージ－マジョラム
- [x] 101010034 - Aromaseraphy Sweet Marjoram - アロマセラフィ－スイート・マジョラム
- [x] 101010059 - Aroma Gardening - アロマガーデニング
- [x] 101010074 - Blessed Winds - 恵みの風

Possibly more coming

**Comment by AlphaKretin** [comment]
I'm taking Laurier

**Comment by AlphaKretin** [comment]
CC has sweet marjoram

**Comment by AlphaKretin** [comment]
I'll do gardening I guess

**Comment by AlphaKretin** [comment]
nvm i didn't finish laurier at all

**Comment by EerieCode** [comment]
I'll do Gardening

**Comment by EerieCode** [comment]
I can do Blessed Winds if no one else is
