### ISSUE TITLE
CHIM Reveals from Duel Live and CM [Scripts]

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#110]
It has been announced that the Duel Live event later tonight will have some reveals of cards from CHIM. On the expectation that there will be multiple, I'm creating this issue now to be ready.
- [x] 101010001 - Suppress Collider (Normal Monster)
- [x] 101010015 - Starcloud Dragon Nebula - 星雲龍ネビュラ
- [x] Dinowrestler Valeonyx - ダイナレスラー・バーリオニクス
- [x] 101010023 - Metal Beak Yata-no-Misaki - 機巧嘴－八咫御先
- [x] 101010038 - Protocol Gardna - プロトコル・ガードナー
- [x] Tachyon Galaxy Spiral - タキオン・ギャラクシー・スパイラル

**Comment by AlphaKretin** [comment]
Dibs on Yata-Garasu and at least one tachyon-ish card

**Comment by AlphaKretin** [comment]
OK said tachyon-ish card will be the nebula thing

**Comment by AlphaKretin** [comment]
Realised I took every card we have text for which is a dick move, releasing the Metal Beak unless I finish Nebula

**Comment by AlphaKretin** [comment]
about to upload nebula, I gotta run, someone else can and in fact please do take yata

**Comment by EerieCode** [comment]
I'll see if I can do it later
