### ISSUE TITLE
Remaining Cards of CHIM [Scripts]

### ISSUE THREAD

**Issue by LogicalNonsense2051** [EerieCode/Percy-Alpha-Testing#112]
The remaining cards of the set, Chaos Impact, has been revealed! This issue is created for us to be aware of who is working on which cards.

- [x] 101010001 - Suppress Collider --サプレス・コライダー
- [x] 101010006 - Dinowrestler Martial Ampelo --ダイナレスラー・マーシャルアンペロ
- [x] 101010007 - DInowrestler Valeolynx --ダイナレスラー・バーリオニクス
- [x] 101010016 - Spiral Dragon Bulge --螺旋竜バルジ **[Tested]**
- [x] 101010022 - Infinitrack Brutal Dozer --無限起動ブルータルドーザー **[Tested]**
- [x] 101010025 - Prometeoron the Burning Astroid --燎星のプロメテオロン
- [x] 101010026 - Brynigle --ブライニグル
- [x] 101010030 - Bayoneter the Magical Scope --魔筒覗ベイオネーター **[Tested]**
- [x] 101010031 - Mimickuril --ミミックリル   **[Tested]**
- [x] 101010032 - Hitori Boushi --独法師
- [x] 101010051 - Salamangreat Burning Shell --転生炎獣の炎虞   **[Tested]**
- [x] 101010062 - Evil Eye of Gorgone --ゴルゴネイオの呪眼
- [x] 101010065 - Spiritual Energy Entanglement --霊子もつれ **[Tested]**
- [x] 101010066 - Old Mind --オールド・マインド
- [x] 101010073 - Tachyon Galaxy Spiral --タキオン・ギャラクシースパイラル **[Tested]**
- [x] 101010076 - Crusher Run --超整地破砕 **[Tested]**
- [x] 101010079 - Soul Levy --ソウル・レヴィ **[Tested]**
- [x] 101010080 - Bangpoline --ドカンポリン

Sources: 
- https://yugipedia.com/wiki/Chaos_Impact
- [Various articles on YGOrganization]
List may need revising; possibly missed some cards to add onto the checklist

**Comment by EerieCode** [comment]
I can do Mimickuril and maybe Old Mind as well

**Comment by LogicalNonsense2051** [comment]
I'll work on Crusher Run and Spiral Dragon Bulge.

**Comment by EerieCode** [comment]
My two cards are done, that's all I can do for now. I'll see if I can do something later, but no guarantees

**Comment by EerieCode** [comment]
Also, I've added to the list the cards from the commercial and Burning Shell. Their effects have been confirmed, so they've already been scripted, but this way we can easily remember they still have to be tested and added to Percy as well.

**Comment by EerieCode** [comment]
Logic is doing the Infinitruck as well

**Comment by LogicalNonsense2051** [comment]
Will work on Spiritual Energy Entanglement and Bayoneter the Magical Scope.

**Comment by EerieCode** [comment]
Martial Ampelo's first effect is identical to the anime, we can use the anime script for that. I can add the second effect later.

**Comment by LogicalNonsense2051** [comment]
"Soul Levy" completed.

**Comment by EerieCode** [comment]
I can script the Eye.

**Comment by EerieCode** [comment]
Eye done, I'll try to script Prometeoron!

**Comment by EerieCode** [comment]
With this all cards have been scripted! I'm closing this issue, we'll use [this](https://github.com/EerieCode/Percy-Alpha-Testing/issues/113) to keep track of the tests.
