### ISSUE TITLE
[Scripts] VJump - July 2019

### ISSUE THREAD

**Issue by EerieCode** [EerieCode/Percy-Alpha-Testing#114]
## Deck Build Pack: Mystic Fighters - 100423XXX 
"Generaid": 0x232
- [x] 100423027 - Mardoll, Generaid of Light --光の王 マルデル
- [x] 100423028 - Fraudir, Generaid of the Sword --剣の王 フローディ
- [x] 100423029 - Dvergs, Generaid of Iron -- 鉄の王 ドヴェルグス
- [x] 100423030 - Naglfar, Generaid of Flames --炎の王 ナグルファー
- [x] 100423031 - Nidhogg, Generaid of Ice -- 氷の王 ニードヘッグ
- [x] 100423032 - Hel, Generaid of Death --死の王 ヘル
- [x] 100423033 - Jormungandr, Generaid of Eternity -- 永の王 オルムガンド
- [x] 100423034 - Generaid Stage -- 王の舞台
- [x] 100423035 - Generaid Quest -- 王の試練
- [x] 100423036 - Generaid Reward --王の報酬
- [x] 100423037 - Generaid Battle --王の襲来
- [x] 100423038 - Generaid Territory --王の支配
- [x] 100423039 - Generaid Bite -- 王の憤激

**Comment by EerieCode** [comment]
Working on Jormungandr

**Comment by AlphaKretin** [comment]
Guess I'll do Mardöll

**Comment by AlphaKretin** [comment]
After much procrastination because omg the rest of these all suck either to play and/or script, I guess I'm going to suck it up and try to do Fraudir

**Comment by AlphaKretin** [comment]
Maybe if I say I'm doing Dvergs, I'll feel like doing it

**Comment by lrhel** [comment]
I will script Hel

**Comment by AlphaKretin** [comment]
Dvergs is half-done - I've uploaded a draft, but it more desperately than usual needs testing and maybe an optimisation pass, the current iteration calls SelectUnselectGroup a *lot*

**Comment by AlphaKretin** [comment]
After that clusterfLIck, it's time to relax with Naglfar

**Comment by AlphaKretin** [comment]
I'll do Nidhogg

**Comment by AlphaKretin** [comment]
Stage

**Comment by AlphaKretin** [comment]
Quest

**Comment by EerieCode** [comment]
I'll try to do Bite

**Comment by EerieCode** [comment]
And Battle too

**Comment by pyrQ** [comment]
Did Reward
