### ISSUE TITLE
[Scripts] RIRA-EN + LINK VRAINS Duelist Set

### ISSUE THREAD

**Issue by NaimSantos** [EerieCode/Percy-Alpha-Testing#117]
----
### RIRA-EN
TCG exclusive cards from [the database](https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=1&sess=1&pid=11118006&rp=99999&request_locale=en)

Dream Mirror: 0x233

- [x] RIRA-EN000 - 101009000 :  "Capshell" **[tested]**
- [x] RIRA-EN081 - 101009081 : "Barricadeborg Blocker" **[tested]**
- [x] RIRA-EN082 - 101009082 : "Hraesvelgr, the Desperate Doom Eagle" **[tested]**
- [x] RIRA-EN083 - 101009083 : "Star Power!!"  **[tested]**
- [x] RIRA-EN084 - 101009084 : "Fuhma Wave" **[tested]**
- [x] RIRA-EN085 - 101009085 : "Ikelos, the Dream Mirror Sprite" **[tested]**
- [x] RIRA-EN086 - 101009086 : "Ikelos, the Dream Mirror Mara" **[tested]**
- [x] RIRA-EN087 - 101009087 : "Morpheus, the Dream Mirror White Knight" **[tested]**
- [x] RIRA-EN088 - 101009088 : "Morpheus, the Dream Mirror Black Knight" **[tested]**
- [x] RIRA-EN089 - 101009089 : "Dream Mirror of Joy" **[tested]**
- [x] RIRA-EN090 - 101009090 : "Dream Mirror of Terror" **[tested]**
- [x] RIRA-EN091 - 101009091 : "Dream Mirror Fantasy" **[tested]**

----
### LINK VRAINS Duelist Set [LVDS]

- [x] 100254001 - Code Exporter - コード・エクスポーター
- [x] 100254003 - Salamangreat Blaze Dragon - 転生炎獣ブレイズ・ドラゴン 
- [x] 100254004 - Bayonet Punisher - ベイオネット・パニッシャー
- [x] 100254006 - Marincess Pascals(?) - 海晶乙女パスカルス
- [x] 100254008 - Dinowrestler Iguanadracker(?) - ダイナレスラー・イグアノドラッカ
- [x] 100254009 - Altergeist Failover - オルターガイスト・フェイルオーバー

**Comment by NaimSantos** [comment]
Eerie wants the lower levels, so 101009085  and 101009086

**Comment by NaimSantos** [comment]
I'm doing Capshell

**Comment by NaimSantos** [comment]
I'm with the two Morpheus

**Comment by lrhel** [comment]
I'm doing Dinowrestler Iguanadracker(?)

**Comment by ahtelel** [comment]
Doing altergeist failover

**Comment by ahtelel** [comment]
Added JP names for cards from Link VRAINS Duelist Set, please add them to the top line of your script when you work on them

**Comment by NaimSantos** [comment]
Doing Barricadeborg Blocker

**Comment by lrhel** [comment]
I will do Code Exporter

**Comment by EerieCode** [comment]
I'll do the Not-Borrel Spell

**Comment by ahtelel** [comment]
Doing salamangreat blaze dragon

**Comment by NaimSantos** [comment]
I'm with the Mirror of Joy

**Comment by lrhel** [comment]
fyi, i unfortunately putted the dinowrestler script in RIRA folder instead of the LVDS

**Comment by lrhel** [comment]
doing Marincess Pascals

**Comment by EerieCode** [comment]
I'll try to do Star Power

**Comment by lrhel** [comment]
Will do Fuhma Wave

**Comment by ahtelel** [comment]
Dream Mirror of Joy done, doing Terror

**Comment by ahtelel** [comment]
Dream Mirror Fantasy left up for grabs

**Comment by EerieCode** [comment]
I'll do Fantasy then
