### ISSUE TITLE
VJump August [Scripts]

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#123]
## Dragonmaid - 1004230XX
- [x] 100423014 - Dragonmaid Nasary - オラゴンメイド・ナサリ
- [x] 100423015 - Dragonmaid Erde - オラゴンメイド・エルデ
- [x] 100423017 - Dragonmaid Frus - オラゴンメイド・フルス
- [x] 100423018 - Dragonmaid Tilul - オラゴンメイド・レィルル
- [x] 100423019 - Dragonmaid Flamme - オラゴンメイド・フランメ
- [x] 100423022 - Dragonmaid Husky - オラゴンメイド・ハスキー
- [x] 100423024 - Reception of the Dragonmaids - オラゴンメイドのお出迎え
- [x] 100423025 - Changing of the Dragonmaids - オラゴンメイドのお召し替え
- [x] 100423026 - Dragonmaid Relaxation - オラゴンメイド・リラクゼーション

**Comment by AlphaKretin** [comment]
Eerie has dibs on Husky

**Comment by NaimSantos** [comment]
I'm taking Dragon Maid Flamme

**Comment by lrhel** [comment]
will do Nasary

**Comment by NaimSantos** [comment]
I will do Dragon Maid Elde

**Comment by NaimSantos** [comment]
I'm taking Frus

**Comment by lrhel** [comment]
will do tilul

**Comment by NaimSantos** [comment]
i'm taking Changing of the Dragon Maids

**Comment by lrhel** [comment]
will try Reception of the Dragonmaids

**Comment by EerieCode** [comment]
I'll try to relax with Relaxation then
