### ISSUE TITLE
Fists of the Gadgets [Scripts]

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#127]
https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=1&sess=1&pid=11118007&rp=99999&request_locale=it
Not currently up in English, hence the Italian.

Important reminders:
 - Fire Fist monsters need their costs to support Eagle
 - "Monster Cards" in card text means original type
## 100255xxx
- [x] 100255001 - Boot-Up Corporal - Command Dynamo
- [x] 100255002 - Boot-Up Admiral - Destroyer Dynamo
- [x] 100255003 - Boot-Up Order - Gear Charge
- [x] 100255004 - Boot-Up Order - Gear Force
- [x] 100255005 - Powerhold the Moving Battery
- [x] 100255011 - Brotherhood of the Fire Fist - Ram
- [x] 100255012 - Brotherhood of the Fire Fist - Elephant
- [x] 100255013 - Brotherhood of the Fire Fist - Panda
- [x] 100255014 - Brotherhood of the Fire Fist - Antelope
- [x] 100255015 -  Brotherhood of the Fire Fist - Swan
- [x] 100255018 - Fire Fortress atop Liang Peak
- [x] 100255019 - Fire Formation - Domei
- [x] 100255020 - Fire Formation - Ingen
- [x] 100255021 - Ultimate Fire Formation - Sinto

**Comment by AlphaKretin** [comment]
I'll do Command Dynamo, I suppose. Gotta start somewhere

**Comment by EerieCode** [comment]
I think I'll do the Fire Fist new bosses and the related Fire Formations. The latter 2 are similar, so might as well do them at once.

**Comment by lrhel** [comment]
I'll start with Start-up Order - Gear Force

**Comment by AlphaKretin** [comment]
I'll do Gear Charge

**Comment by ahtelel** [comment]
Doing Fire Fortress

**Comment by AlphaKretin** [comment]
Doing Powerhold

**Comment by lrhel** [comment]
Will do Sinto

**Comment by EerieCode** [comment]
I think I'll do Ram then

**Comment by lrhel** [comment]
Will try Destroyer Dynamo 🤔

**Comment by lrhel** [comment]
Will do Elephant

**Comment by lrhel** [comment]
I will do the last one: Panda
