### ISSUE TITLE
VJump September 2019 Day 1 [Scripts]

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#134]
## Structure Deck R - Warrior's Strike - 1003090XX
- [x] 100309003 - Flame Noble Knight Roland - 焔聖騎士-ローラン
- [x] 100309021 - Gearbreed - 武装鍛錬
- [x] 100309022 - Raptinus’ Supreme Magicblade - ラプテノスの超魔剣

## IGNITION ASSAULT (@Ignister) - 1010110XX
@Ignister: 0x234
A.I.: 0x235
- [x] 101011001 - Pikari @Ignister - ピカリ＠イグニスター
- [x] 101011002 - Bururu @Ignister - ブルル＠イグニスター
- [x] 101011003 - Doyon @Ignister - ドヨン＠イグニスター
- [x] 101011004 - Achichi @Ignister - アチチ＠イグニスター
- [x] 101011005 - Hiyari @Ignister - ヒヤリ＠イグニスター
- [x] 101011006 - Doshin @Ignister - ドシン＠イグニスター
- [x] 101011034 - Water Leviathan @Ignister - ウォーターリヴァイアサン＠イグニスター
- [x] 101011041 - Earth Golem @Ignister - アースゴーレム＠イグニスター
- [x] 101011042 - Wind Pegasus @Ignister - ウィンドペガサス＠イグニスター
- [x] 101011050 - Ignister A.I.Land - イグニスターＡｉランド
- [x] 101011052 - A.I.dle Reborn - Ａｉドリング・ボーン
- [x] 101011053 - A.I. Love Fusion - Ａｉラブ融合
- [x] 101011054 - A.I.'s Ritual - Ａｉの儀式

## IGNITION ASSAULT (Karakuri) - 1010110XX
- [x] 101011014 - Karakuri Monk mdl 9763 "Kunamusan" - カラクリ法師 九七六参
- [x] 101011015 - Karakuri Toad mdl 4624 "Shirokunishi" - カラクリ蝦蟇 四六弐四
- [x] 101011043 - Karakuri Daigongen mdl 00X "Bureibu" - カラクリ大権現 無零武
- [x] 101011058 - Karakuri Toad Oil - カラクリ蝦蟇油
- [x] 101011073 - Karakuri Cash Lodge - 借カラクリ旅籠蔵

**Comment by AlphaKretin** [comment]
I guess I'll do Raptinus' sord

**Comment by LogicalNonsense2051** [comment]
Working on "Flame Noble Knight Roland".

**Comment by AlphaKretin** [comment]
In that case, I'll close this set out with Gearbreed

**Comment by EerieCode** [comment]
I'm doing Pikari

**Comment by LogicalNonsense2051** [comment]
Will take "Doshin @Ignister".

**Comment by AlphaKretin** [comment]
I'll do Bururu. Remember that you can likely adapt from the anime version partially.

**Comment by LogicalNonsense2051** [comment]
For now, will do "Doyon @Ignister", since Doshin hasn't been translated yet (and from the looks, will take some time).

**Comment by AlphaKretin** [comment]
I'll do Achichi

**Comment by EerieCode** [comment]
I'll do Hiyari

**Comment by EerieCode** [comment]
Hiyari done, doing Ailand

**Comment by AlphaKretin** [comment]
I'll do Aidle Reborn

**Comment by EerieCode** [comment]
Doing Leviathan

**Comment by AlphaKretin** [comment]
Hopefully Eerie isn't about to claim it at the same time, but I'll take Wind Pegasus

**Comment by EerieCode** [comment]
Go ahead, I won't be able to script for at least one hour

**Comment by ClementLouis** [comment]
claiming the Karakuri synchro

**Comment by LogicalNonsense2051** [comment]
Will take the level 1 tuner Karakuri.

**Comment by MichaelLawrenceDee** [comment]
Will take the Karakuri supports

**Comment by AlphaKretin** [comment]
I guess I've got the monk, then

**Comment by AlphaKretin** [comment]
With MLD claiming both remaining Karakuri cards, we're close to finished. I think I might see if we can leave Earth Golem to Larry, unless it gets late and he never shows, and I want to leave one of the remaining cards to aht. Let's say I'll do A.I.'s Ritual, and aht can take A.I. Love Fusion.
