### ISSUE TITLE
VJump October[Scripts]

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#136]
## IGAS - Romance of the Three Kingdoms theme - 1010110XX
Senka: 0x236
Org translations: https://ygorganization.com/romanceofthreekingdoms/
- [x] 101011008 - Son Bou
- [x] 101011009 - Juu Kou
- [x] 101011010 - U Gei
- [x] 101011011 - Ryu Gen
- [x] 101011012 - Kan Un
- [x] 101011013 - Chou Toku
- [x] 101011055 - First cont spell
- [x] 101011056 - Second cont spell
- [x] 101011070 - Cont trap

## IGAS - Megalith theme 
- [x] 101011035 Megalith Ophel
- [x] 101011036 Megalith Hagit
- [x] 101011037 Megalith Oc
- [x] 101011038 Megalith Fareg
- [x] 101011039 Megalith Bedoll
- [x] 101011040 Megalith Alatron
- [x] 101011057 Megalith Portal
- [x] 101011071 Megalith Promotion
- [x] 101011072 Megalith Emersion

## CHIM

- [x] 101010000 Monster Express
- [x] 101010081 Primineral Mandstrong
- [x] 101010082 Desert Locusts
- [x] 101010083 Tyrant Farm
- [ ] 101010084 Brutal Beast Battle
- [ ] 101010085 Phantasos The Dream Mirror Friend
- [x] 101010086 Phantasos The Dream Mirror Foe
- [x] 101010087 Oneiros, the Dream Mirror Erlking
- [x] 101010088 Dream Mirror Phantasms
- [x] 101010089 Dream Mirror of Chaos
- [x] 101010090 Dream Mirror Hypnagogia
- [x] 101010091 Dream Mirror Oneiromancy

**Comment by ahtelel** [comment]
Doing three visit

**Comment by AlphaKretin** [comment]
Doing the cont spell 056

**Comment by NaimSantos** [comment]
I'm with Megalith Emersion atm

**Comment by ClementLouis** [comment]
I'm taking Megalith Portal

**Comment by lrhel** [comment]
will do Megalith Alatron

**Comment by NaimSantos** [comment]
Taking Megalith Promotion

**Comment by ahtelel** [comment]
Wil do Phaleg

**Comment by NaimSantos** [comment]
Requesting Megalith Bedoll

**Comment by NaimSantos** [comment]
I'm taking Tyrant Farm

**Comment by EerieCode** [comment]
I'm doing Oneiros

**Comment by lrhel** [comment]
I will do Phantasos, the Dream Mirror Foe

**Comment by EerieCode** [comment]
Oneiros done, I'l start working on the DM Spells

**Comment by NaimSantos** [comment]
Im taking  Monster Express

**Comment by EerieCode** [comment]
DM Spells done, I'll work on the Traps

**Comment by NaimSantos** [comment]
doing Primineral Mandstrong
