### ISSUE TITLE
IGAS October [Scripts]

### ISSUE THREAD

**Issue by kevinlul** [EerieCode/Percy-Alpha-Testing#137]
https://ygorganization.com/notenyipensiveface/
https://ygorganization.com/imsobossypleasegetoffme/
https://www.reddit.com/r/yugioh/comments/dg89d3/igas_remaining_new_cards_from_ignition_assault/
## Ignition Assault - 1010110XX - scripts
- [x] 101011018 - Time Thief Time Recorder - クロノダイバー・タイムレコーダー (dib by Cybercatman)
- [x] 101011025 - Cataclysmic Cheerful Calcragra - 楽天禍カルクラグラ
- [x] 101011026 - Jack A’ Booran - ジャック・ア・ボーラン
- [x] 101011027 - Evilcella Lutea -イビルセラ・ルテア
- [x] 101011028 - Uvaloop the Obsession - 執愛のウヴァループ
- [x] 101011029 - Daruma Otoshi - 達磨落師 (dib by LogicalNonsense)
- [x] 101011030 - Transcicada - トランシケーダ
- [x] 101011031 - Tune Knight - チューン・ナイト
- [x] 101011032 - Battle Survivor - バトル・サバイバー  (dib by MLD)
- [x] 101011033 - Cupid Serve - テイ・キューピット (dib by AlphaKretin)
- [x] 101011047 - Clotheep - クロシープ
- [x] 101011049 - Gravity Controller - グラビティ・コントローラー
- [x] 101011062 - Sky Striker Maneuver - Scissors Cross - 閃刀術式-シザーズクロス (dib by Cybercatman)
- [x] 101011065 - Disposable Learning Device - 使い捨て学習装置
- [x] 101011068 - Fragile-Edged Sword - 脆刃の剣 (dib by MLD)
- [x] 101011079 - Devil’s Portrait - 幻魔の肖像
- [x] 101011080 - Head Judging - ヘッド・ジャッジング

## Tested
- [x] 101011018 - Time Thief Time Recorder
- [x] 101011025 - Cataclysmic Cheerful Calcragra 
- [x] 101011026 - Jack A’ Booran
- [x] 101011027 - Evilcella Lutea
- [x] 101011028 - Uvaloop the Obsession 
- [x] 101011029 - Daruma Otoshi
- [x] 101011030 - Transcicada
- [x] 101011031 - Tune Knight
- [x] 101011032 - Battle Survivor
- [x] 101011033 - Cupid Serve
- [x] 101011047 - Clotheep
- [x] 101011049 - Gravity Controller
- [x] 101011062 - Sky Striker Maneuver - Scissors Cross
- [x] 101011065 - Disposable Learning Device
- [x] 101011068 - Fragile-Edged Sword
- [x] 101011079 - Devil’s Portrait
- [x] 101011080 - Head Judging

**Comment by MichaelLawrenceDee** [comment]
Reserving Lutea

**Comment by kevinlul** [comment]
@AlphaKretin claims Clotheep

**Comment by AlphaKretin** [comment]
Claiming Clotheep

**Comment by kevinlul** [comment]
@ClementLouis claims Sky Striker Maneuver - Scissors Cross and Time Thief Time Recorder

**Comment by MichaelLawrenceDee** [comment]
Claiming Gravity Controller

**Comment by LogicalNonsense2051** [comment]
Claiming Transicicada.

**Comment by MichaelLawrenceDee** [comment]
Claiming Tune Knight

**Comment by LogicalNonsense2051** [comment]
Claiming Uvaloop the Obsession and Cataclysmic Cheerful Calcragra.

**Comment by ahtelel** [comment]
Doing Devil portrait

**Comment by LogicalNonsense2051** [comment]
Working on Daruma Otoshi.

**Comment by AlphaKretin** [comment]
Doing Cupid Serve

**Comment by ahtelel** [comment]
Doing Disposable Learning Device
