### ISSUE TITLE
VJump October LED6

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#138]
https://yu-gi-oh.jp/index.php?page=details&&id=668
https://imgur.com/a/FNqV0yP

### 100413012 - Elemental HERO Sunriser - E・HERO サンライザー
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100413015 - Favorite Hero - フェイバリット・ヒーロー
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100413016 - Magistry Alchemist - マジスタリー・アルケミスト
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100413023 - Satellite Warrior - サテライト・ウォリアー
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100413025 - Satellite Synchron - サテライト・シンクロン
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100413027 - Scrap-Iron Signal - くず鉄のシグナル
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100413034 - Gagagaga Magician - ガガガガマジシャン
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100413036 - Dododo Dwarf - Gogogo Glove - ドドドドワーフ-GG
- [x] Claimed
- [x] Scripted
- [ ] Tested
### 100413038 - Future Drive - フューチャー・ドライブ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100413045 - Performapal Celestial Magician - EM天空の魔術師
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100413048 - Smile Action - スマイル・アクション
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100413049 - Pendulum Dimension - ペンデュラム・ディメンション
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by AlphaKretin** [comment]
CC wants Sat. Warrior, I want Scrap-Iron Signal, Eerie wants Celestial Magician if it's scriptable

**Comment by EerieCode** [comment]
I'm claiming Future Drive and Pendulum Dimension. Celestial magician can't be done, the watermark is covering half of the Pendulum effect

**Comment by ClementLouis** [comment]
I'm also claiming satellite synchron since i need it for warrior

**Comment by AlphaKretin** [comment]
Claiming Favorite Hero too, since we're all claiming two

**Comment by EerieCode** [comment]
I'll do Celestial Magician too, since apparently we have the Pendulum effect somehow

**Comment by AlphaKretin** [comment]
I've got a trainee working on Favorite Hero, I'm going to do Smile Action

**Comment by EerieCode** [comment]
I'm retracting my claim of Pendulum Dimension, it's up for grabs

**Comment by ahtelel** [comment]
Doing Sunriser

**Comment by that-hatter** [comment]
I'll do Dododo

**Comment by lrhel** [comment]
Claiming Gagagaga Magician :eyes:

**Comment by pyrQ** [comment]
Doing "Magistry Alchemist"..

**Comment by EerieCode** [comment]
Since no one claimed it, I'll reclaim Pendulum Dimension. Will do it as soon as I return home
