### ISSUE TITLE
VJump October LVP3 + LGB1

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#139]
### 100257001 - Link God Dragon - L・G・D
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100257036 - Selene, the Mighty Mistress of Magic - 神聖魔皇后セレーネ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100257071 - Predaplant Verte Anaconda - 捕食植物ヴェルテ・アナコンダ
- [x] Claimed
- [x] Scripted
- [x] Tested

### 100259001 - Dragoon of Red-Eyes - 超魔導竜騎士－ドラグーン・オブ・レッドアイズ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100259009 - Elemental HERO Neos Krueger - E・HERO ネオス・クルーガー
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100259017 - Shooting Star Dragon - TG Expansion - シューティング・スター・ドラゴン・TG-EX
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by AlphaKretin** [comment]
Eerie had LGD, I have Selene

**Comment by NaimSantos** [comment]
Claiming the Predaplant
