### ISSUE TITLE
VJump November Link Vrains Pack 3

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#141]
## Link Vrains Pack 3 - 1002570XX  
https://yu-gi-oh.jp/index.php?page=details&&id=688
https://ygorganization.com/lmaodinosaurpyrorock/
### 100257011 - Union Carrier - ユニオン・キャリアー
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100257016 - Ancient Gear Ballistic Shooter - 古代の機械弩士
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100257031 - Xtra HERO Infernal Divisor - X・HEROヘル・デバイサー
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100257046 - Reptilianne Echidna - エキドゥーナ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100257066 - Bloom Harmonist the Melodious Virtuoso - 幻奏の華楽聖ブルーム・ハーモニスト
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by AlphaKretin** [comment]
I'm on the Union, Larry's on the HERO, aht's on the Rept, Eerie's on the Melo

**Comment by LogicalNonsense2051** [comment]
Will do Ancient Gear then.
