### ISSUE TITLE
VJump November Legendary Gold Box

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#143]
## Legendary Gold Box - 1002590XX
https://ygorganization.com/itsdragonsallthewaydownchief/
### 100259025 - Number F0: Utopic Dragon Future - FNo.0 未来龍皇ホープ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100259033 - Odd-Eyes Rebellion Dragon Overlord - 覇王黒竜オッドアイズ・リベリオン・ドラゴン－オーバーロード
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100259041 - Decode Talker Heatsoul - デコード・トーカー・ヒートソウル
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by AlphaKretin** [comment]
I claimed F0, CC claimed Heatsoul, Eerie's got Overlord

**Comment by AlphaKretin** [comment]
Preliminary test: Number F0's effect to negate an activation can't activate.

**Comment by kevinlul** [comment]
Decode Talker Heatsoul, line 5: attempt to index nil global `Link`. That proc isn't here

**Comment by kevinlul** [comment]
Overlord is missing an end parenthesis on Line 91

**Comment by kevinlul** [comment]
Overlord's effect is destroying all cards in the Pendulum Zones and then placing itself in the scale. It does not destroy. This effect is like Raging, not Rebellion.

**Comment by kevinlul** [comment]
Overlord summon dbstring missing.

**Comment by kevinlul** [comment]
- [ ] Overlord scale effect is incredible buggy. Any Extra Deck card (face-up or face-down) can be selected and then the summon procedure fails to complete, leaving the card itself as an Xyz Material on the field without being attached to anything.

**Comment by AlphaKretin** [comment]
- [ ] Heatsoul missing a database string for choosing whether or not to summon a Link Monster. Script is now fine though so I'll mark it tested
