### ISSUE TITLE
VJump November Premium Pack 2020

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#145]
## Premium Pack 2020 - 1002290XX
https://yu-gi-oh.jp/index.php?page=details&&id=691
### 100229001 - Gilti-Gearfriend the Magical Steel Knight - 鋼鉄の魔導騎士-ギルティギア・フリード
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100229002 - Crystal Girl - クリスタル・ガール
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100229003 - Altergeist Memorygant - オルターガイスト・メモリーガント
- [x] Claimed
- [x] Scripted
- [ ] Tested
### 100229007 - Rose Princess - ローズ・プリンセス
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100229011 - White Rose Cloister - 白薔薇の回廊
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by AlphaKretin** [comment]
Naim claims Gilti-Gearfried, I'm claiming White Rose Cloister. Logic wants an unspecified card, and Eerie probably does too?

**Comment by EerieCode** [comment]
Actually, I said I'd take Cloister...

**Comment by AlphaKretin** [comment]
Sorry, my bad! I'll take Crystal Girl then. Scripters please note that Memorygant has an anime version

**Comment by LogicalNonsense2051** [comment]
Alright, I guess I'll take the Rose monster.

**Comment by AlphaKretin** [comment]
Preliminary testing: Altergeist Memorygant can activate its effect during the Main Phase

**Comment by AlphaKretin** [comment]
I made a mistake with the IDs and Rose Princess needs to search -011, not -008. Sorry. Otherwise seems to work fine, will test Cloister now.

**Comment by NaimSantos** [comment]
Memorigant has no effect activatable in the Main Phase @AlphaKretin
