### ISSUE TITLE
Link Vrains Pack 3 Livestream

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#146]
### 100257021 - Mirage Herald - 虚光の宣告者
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100257026 - Simorgh, King of Birds - 王神鳥シムルグ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100257051 - Mecha Phantom Beast Auroradon - 幻獣機アウローラドン
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100257056 - [Bujin] - JP NAME
- [x] Claimed
- [x] Scripted
- [ ] Tested
### 100257061 - Artifact Dagda - アーティファクト-ダグザ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100257076 - Abyss Actor - Hyper Director - 魔界劇団-ハイパー・ディレクター
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100257086 - Sky Striker Ace - Sieg - 閃刀姫-ジーク
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100257091 - [Mayakashi] - 零氷の魔妖-雪女
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100257096 - Tenyi Spirit - Sahasrara - 天威龍-サハスラーラ
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by ClementLouis** [comment]
I'll Reserve the Mayakashi one now to avoid not being able later if i get busy during the stream

**Comment by AlphaKretin** [comment]
Feeling in a Simorgh mood, myself

**Comment by ahtelel** [comment]
Taking bujin

**Comment by AlphaKretin** [comment]
Larry wants Tenyi but will pass if he doesn't appear within 20 minutes of its reveal, Logic is taking Artifact

**Comment by AlphaKretin** [comment]
We should also keep in mind to save Eerie one

**Comment by EerieCode** [comment]
If we're pre-claiming, I'll have the Abyss Actor

**Comment by NaimSantos** [comment]
Claiming Herald

**Comment by NaimSantos** [comment]
The Artifact monster needs a better handling for "the end phase of the opponent's next turn"
Usually, we can pass the turn count as label and do the maths with it in the condition, but with this, the script already used the FieldID as label to look for the card to destroy. Basically: atm, it will destroy the card in the first end phase reached. 

The Sky Striker monster is not returning the monster banished to the field
