### ISSUE TITLE
VJump December LGB1

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#148]
## Legendary Gold Box - 1002590XX
https://yu-gi-oh.jp/index.php?page=details&id=703
### 100259005 - Deep of Blue-Eyes - 深淵の青眼龍
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100259013 - Rainbow Dragon the Zenith Crystal beast - 究極宝玉獣 レインボー・ドラゴン
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100259021 - Red Supernova Dragon - スカーレッド・スーパーノヴァ・ドラゴン
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100259029 - Galaxy-Eyes Afterglow Dragon - 銀河眼の残光竜
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100259037 - D/D/D Eulogy King Vice Requiem - DDD死謳王バイス・レイクエム
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100259045 - Borrelend Dragon - ヴァレル・エンド・ドラゴン
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by AlphaKretin** [comment]
I've got supernova, aht has Afterglow, Eerie has Borrelend. Larry is deciding between Blue-Eyes and Rainbow Dragon, and Logic and Hel have claim to the remainders

**Comment by AlphaKretin** [comment]
Larry took Blue-Eyes in the end

**Comment by ahtelel** [comment]
For the CDB maker(s): For GE Afterglow, counting from 0:
String 2: Attach
String 3: Special Summon

**Comment by NaimSantos** [comment]
Claiming D/D/D Eulogy King Vice Requiem
