### ISSUE TITLE
VJump December 20PP

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#149]
## Premium Pack 2020 - 1002290XX
https://yu-gi-oh.jp/index.php?page=details&&id=705
https://ygorganization.com/dholesequalsdolls/
### 100229006 - Tindangle Dholes - ティンダングル・ドールス
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100229009 - Right Hand Shark - ライトハンド・シャーク
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100229010 - Left Hand Shark - レフトハンド・シャーク
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100229016 - Pendulum Xyz - ペンデュラム・エクシーズ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100229017 - Dowsing Fusion - ダウジング・フュージョン
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100229018 - White Mirror - 白の水鏡
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100229020 - Eternal Bond - エターナル・ボンド
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by AlphaKretin** [comment]
I'm all over that Tindangle

**Comment by AlphaKretin** [comment]
Eerie has pend xyz

**Comment by AlphaKretin** [comment]
Speak up if anyone wants to do the sharks - I'm gonna prepare dinner them claim one

**Comment by AlphaKretin** [comment]
Taking RHShark as promised

**Comment by EerieCode** [comment]
Xyz done, claiming Dowsing Fusion

**Comment by AlphaKretin** [comment]
Claiming White Mirror

**Comment by NaimSantos** [comment]
Taking Eternal Bond
