### ISSUE TITLE
VJump December ETCO

### ISSUE THREAD

**Issue by larry126** [EerieCode/Percy-Alpha-Testing#150]
## Eternity Code- 1010120XX
https://yu-gi-oh.jp/index.php?page=details&&id=705
https://ygorganization.com/etcosenkanews/
### 101012020 - Senka no Mou – Soutoku / Senka Chief – Cao De - 戦華の孟－曹徳
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012021 - Senka no Rai – Chouen / Senka Herald – Zhang Yuan - 戦華の来－張遠
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012022 - Senka no Ki – Kabun / Senka Machinator – Jia Wen - 戦華の詭－賈文
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012023 - Senka no Chi – Shokatsukou / Senka Strategist – Zhuge Kong - 戦華の智－諸葛孔
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012069 - Senka Shiryaku – Juuman no Ya / Senka Legend – One Hundred Thousand Arrows - 戦華史略－十万之矢
- [x] Claimed
- [x] Scripted
- [x] Tested
##
### 101012013 - Deep Sea Artisan - 深海のアーチザン
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012014 - Deep Sea Sentry -深海のセントリー
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012015 - Deep Sea Minstrel - 深海のミンストレル
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012042 - Deep Sea Princess Prima Donna - 深海姫プリマドーナ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012061 - Deep Sea Aria - 深海のアリア
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by larry126** [comment]
101012023 claimed by Larry

**Comment by larry126** [comment]
Dib on Senka Chief – Cao De

**Comment by larry126** [comment]
Senka Herald – Zhang Yuan

**Comment by larry126** [comment]
doing Senka Legend – One Hundred Thousand Arrows

**Comment by larry126** [comment]
Deep Sea Princess Prima Donna claimed by Eerie

**Comment by AlphaKretin** [comment]
Claiming Deep Sea Aria, but I’ll release it if everything’s ready and I’m not back from locals yet

**Comment by EerieCode** [comment]
Tentatively claiming Artisan

**Comment by NaimSantos** [comment]
Taking Deep Sea Minstrel and Deep Sea Sentry

**Comment by NaimSantos** [comment]
Taking Senka Machinator - Jia Wen
