### ISSUE TITLE
Miscellaneous Jump Festa Reveals

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#151]
### 100229005 - Altergeist Fijialert - オルターガイスト・フィジアラート
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100229008 - Morph King Stygi-Gel - 変容王ヘル・ゲル
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100229012 - Burning Soul - バーニング・ソウル
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100229013 - Hidden Fangs of Revenge - 報復の隠し歯
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100229015 - Pendulum Transfer - ペンデュラム・シフト
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100229019 - The Ice-Bound God - 神の氷結
- [x] Claimed
- [x] Scripted
- [x] Tested

### 100261001 - Dazzling Lunar Dragon Selegrea - 眩月龍セレグレア
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100261002 - Selkie the Living Memory - 生きる偲びのシルキィ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100261003 - Rhynosaber the Mad-Dash Armory - 驀進装甲ライノセイバー
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100261004 - Potluck Party - 闇味鍋パーティー
- [x] Claimed
- [x] Scripted
- [x] Tested

### 101012045 - Traptrix Allomerus - アロメルスの蟲惑魔
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012051 - Codebreaker Virus Berserker - コードブレイカー・ウイルスバーサーカー
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012041 - Dragonmaid Strahl - ドラゴンメイド・シュトラール
- [x] Claimed
- [x] Scripted
- [ ] Tested
### 101012040 - Invoked Augoeides - 召喚獣アウゴエイデス
- [x] Claimed
- [x] Scripted
- [x] Tested

### 100263001 - Gussari @Ignister - グッサリ＠イグニスター
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100263002 - Gatchiri @Ignister - ガッチリ＠イグニスター
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by AlphaKretin** [comment]
Tentatively claiming Stygi-Gel but I'll be out most of the day so usual caveat that I'll release it if we're just waiting on me

**Comment by AlphaKretin** [comment]
To be clear this issue is also intended for if the live streams this weekend reveal cards in other sets, just add a new heading

**Comment by that-hatter** [comment]
Taking Burning Soul

**Comment by LucasHilarioFavaroLeal** [comment]
I have scripted Pendulum Transfer, need a way to submit it

**Comment by ahtelel** [comment]
Before you do anything, first you check [Claimed] the card you want to do in the top post in the issue; then once you're done you upload it to the corresponding folder then check [Scripted]

**Comment by KingYamato** [comment]
Well, I can't check the field

**Comment by ahtelel** [comment]
@EerieCode Can you give @KingYamato collaborator access to this repo? They are a welcome addition to the team

**Comment by ahtelel** [comment]
Taking Rhynosaber

**Comment by KingYamato** [comment]
Thanks aht and thanks Eerie in advance 🙇

**Comment by EerieCode** [comment]
@KingYamato I sent you an invitation.

As for me, I'm claiming Hidden Fangs of Revange

**Comment by AlphaKretin** [comment]
I guess I'll take Virus Berserker, for all the good it does on its own

**Comment by EerieCode** [comment]
@AlphaKretin If you're doing the Codebreaker, the archetype is 0x23B.

As for me, I'll quickly do the Ignisters: they're similar to the anime, so I just need to adapt them a little

**Comment by AlphaKretin** [comment]
Codebreaker Virus Berserker is untested and very wack, summoning multiple monsters to either side of the field sucks. Very much needs testing and possibly could be refactored

**Comment by AlphaKretin** [comment]
BTW, who claimed the Traptrix?

**Comment by LogicalNonsense2051** [comment]
I did.

**Comment by AlphaKretin** [comment]
Claiming Selkie the Living Memory

**Comment by AlphaKretin** [comment]
Taking Dazzling Lunar Dragon Selegrea

**Comment by AlphaKretin** [comment]
Taking Ice-Bound God

**Comment by EerieCode** [comment]
Tentatively claiming Potluck Party, not 100% sure if it's scriptable though

**Comment by EerieCode** [comment]
Potluck done, I'll do the Altergeist and then we can start testing

**Comment by ahtelel** [comment]
Testing all PP20 cards

**Comment by EerieCode** [comment]
I'm testing the Ignisters

**Comment by EerieCode** [comment]
Ignisters tested, testing the Potluck

**Comment by ahtelel** [comment]
Everything is ready. Close when adding

**Comment by ahtelel** [comment]
Issue has been updated with 2 new cards from ETCO. Claiming the Invoked fusion

**Comment by KingYamato** [comment]
Claiming Dragonmaid Strahl
