### ISSUE TITLE
Jump Festa Scripted Duel

### ISSUE THREAD

**Issue by ClementLouis** [EerieCode/Percy-Alpha-Testing#152]
Those effects are made from the transcript of the Scripted duel of the Jump Festa, so likely not complete and/or will be slighly different when released officially

Crimson Resonator: cydra like summoning cond. If you use a Dark dragon synchro monster as the other material, you can special summon 2 resonator from deck except crimson.
PSCT version
(1) If your opponent controls a monster, you can special summon this card from your hand.(?)
(2) If this card was sent to the GY as Synchro Material with a DARK Dragon Synchro monster, you can special summon 2 Resonator monsters from your deck except Crimson Resonator.(?)
- [x] Claimed
- [x] Scripted
- [ ] Tested

Scar red familiar
When normal summoned, you can special summon an RDA from the GY. You can banish it from GY to make a RDA level 6
- [x] Claimed
- [x] Scripted
- [ ] Tested

Lantern Shark: when normal summoned, special summon 1 Level 3 to 5 water monster from your hand
- [x] Claimed
- [x] Scripted
- [ ] Tested

Cutter Shark: if used as Xyz Material, can be treated as any level between 3 to 5
- [x] Claimed
- [x] Scripted
- [x] Tested

Valiant Shark Lancer: destroy 1 monster on the field, this effect become quick if you control another Water Xyz monster
- [x] Claimed
- [x] Scripted
- [ ] Tested

Nocto Vision Dragon (not a lot of info about that one, likely the same as anime)
Defensive power 2800 Level 5 or higher because it can be revived by twin tries
1 draw when it becomes link material
- [x] Claimed
- [ ] Scripted
- [ ] Tested

**Comment by ClementLouis** [comment]
Claiming the two Jack Cards

**Comment by AlphaKretin** [comment]
I'll draft Lantern and Valiant, knowing Cutter might not be possible

**Comment by EerieCode** [comment]
I'll try to do Cutter, at least to see if it really _is_ impossible.

**Comment by LogicalNonsense2051** [comment]
Will make changes to Nocto Vision Dragon if necessary.

**Comment by AlphaKretin** [comment]
The only card not accounted for here by the XMas reveals is Noctovision Dragon, which already has an anime draft. Closing.
