### ISSUE TITLE
XMas Revealsmas [Scripts]

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#153]
### 101012028 - Loptyr, Generaider Boss of Shadows - JP NAME
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012016 - Red Familiar - スカーレッド・ファミリア
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012017 - Crimson Resonator - クリムゾン・リゾネーター
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012062 - Resonator Command - コマンド・リゾネーター
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012074 - Red Reign/Rain - スカーレッド・レイン
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012018 - Lantern Shark - ランタン・シャーク
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012019 - Cutter Shark - カッター・シャーク
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012044 - Valiant Shark Lancer - ヴァリアント・シャーク・ランサー
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012063 - Air Torpedo - エアー・トルピード
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012075 - Xyz Revive Splash - エクシーズ・リバイブ・スプラッシュ
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by AlphaKretin** [comment]
Red Familiar and Crimson Resonator drafted by CC
Lantern Shark and Bariant Shark Lancer drafted by AlphaKretin
Cutter Shark drafted by EerieCode, and he also claimed Red Reign
Resonator Command, Air Torpedo and Xyz Revive Splash up for grabs

**Comment by larry126** [comment]
Claim Resonator Command

**Comment by AlphaKretin** [comment]
I didn't want to get greedy, but it doesn't seem like anyone else is immediately interested, so I'll tackle Xyz Revive Splash

**Comment by larry126** [comment]
Claim Air Torpedo

**Comment by AlphaKretin** [comment]
Lantern Shark cannot be treated as Level 5, even with the workaround devised by Eerie and edo the other night
