### ISSUE TITLE
ETCO Leaks

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#156]
### 101012004 - Gouki Iron Claw - 剛鬼アイアン・クロー
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012005 - Gouki Guts - 剛鬼ガッツ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012007 - Noctovision Dragon - ノクトビジョン・ドラゴン
- [x] Claimed
- [x] Scripted
- [ ] Tested
### 101012024 - Girsu, Mekk-Knight Orcust of the Nightfall Star - 宵星の騎士ギルス
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012025 - Thunder Dragonsky - 天雷震龍-サンダー・ドラゴン
- [x] Claimed
- [x] Scripted
- [ ] Tested
### 101012027 - Hoárr, Generaider Boss of Rumbling - 轟の王ハール
- [x] Claimed
- [x] Scripted
- [ ] Tested
### 101012032 - Trice Hierarchia - トリアス・ヒエラルキア
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012033 - Cataclysmic Chilling Chillbrain - 氷天禍チルブレイン
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012038 - Landscaper Golidlocks - 百景戦都ゴルディロックス
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012039 - Magical Hound - マジカル・ハウンド
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012053 - Gouki the Powerload Ogre - 剛鬼ザ・パワーロード・オーガ
- [ ] Claimed
- [ ] Scripted
- [ ] Tested
### 101012054 - Marincess Great Bubble Reef - 海晶乙女グレート・バブル・リーフ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012057 - Burning Draw - 逆巻く炎の宝札
- [x] Claimed
- [x] Scripted
- [ ] Tested
### 101012059 - Stairs of Mail - メールの階
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012064 - Madolche Salon - マドルチェ・サロン
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012066 - Heavy Forward - 超重機回送
- [x] Claimed
- [x] Scripted
- [ ] Tested
### 101012077 - Witchcrafter Patronus - ウィッチクラフト・パトローナス
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101012079 - Titanocider - 巨神封じの矢
- [x] Claimed
- [x] Scripted
- [ ] Tested
### 101012080 - Pinpoint Dash - ピンポイント奪取
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by AlphaKretin** [comment]
I believe Logic has claim to Noctovision Dragon from some old issue, AND YOU BET I'M TAKING GIRSU

**Comment by lrhel** [comment]
Will take Magical Hound

**Comment by KingYamato** [comment]
Claiming Heavy Forward

**Comment by AlphaKretin** [comment]
I believe Eerie would want Great Bubble Reef

**Comment by pyrQ** [comment]
I can't decide and I g2g to sleep so I'm fine with any of these:
Trice Hierarchia
Madolche Salon
Witchcrafter Patronus
Titanocider
Pinpoint Dash

I'll just see what was left when I get up.

**Comment by ahtelel** [comment]
To help you choose I'll claim Salon

**Comment by ahtelel** [comment]
BIG RECYCLER WITCHCRAFTER TRAP. I'd wager that @NaimSantos would like it.

**Comment by AlphaKretin** [comment]
I'm heading out soon, can someone add Burning Draw and Hoarr to the issue? Note that they have draft scripts already

**Comment by EerieCode** [comment]
Confirm the claim on Reef, and I think I'll do Hierarchia

**Comment by larry126** [comment]
Claim Titanocider

**Comment by EerieCode** [comment]
I'll do Pinpoint Dash

**Comment by NaimSantos** [comment]
I'm taking Witchcrafter Patronus

**Comment by NaimSantos** [comment]
Taking Gouki Iron Claw, which has an anime version

**Comment by NaimSantos** [comment]
Taking Gouki Guts

**Comment by NaimSantos** [comment]
Attempting to do Landscaper Golidlocks

**Comment by ahtelel** [comment]
Tested the following: Stairs of Mail, Trice, Cataclysmic Chillbrain, Magical Hound, Madolche Salon, Pinpoint Dash, Girsu
