### ISSUE TITLE
VJump Janurary SR10

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#158]
### 100310001 - Machina Kernel - マシンナーズ・カーネル
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100310002 - Machina Air Raider - マシンナーズ・エアレイダー
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100310003 - Machina Radiator - マシンナーズ・ラディエータ
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by AlphaKretin** [comment]
CC claims air raider

**Comment by AlphaKretin** [comment]
I guess I'll claim radiator because idc about machina enough to want the beeg boss

**Comment by AlphaKretin** [comment]
Giving up radiator because it's a near copy of airraider, with intent to have CC's raider script just edited slightly. Taking colonel after all instead

**Comment by pyrQ** [comment]
Tested (and fixed stuff for) all three.
