### ISSUE TITLE
VJump January DBSS

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#159]
## Deck Build Pack: Secret Slayers - 100414XXX
Adamacia: `0x23e`
### 100414001 - Adamacia Seeker --魔救の追求者
aka Blue Human
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414006 - Adamacia Crysta - Dragite --魔救の奇石－ドラガイト
aka Blue Rock
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414009 - Adamacia Rise - Dragite --魔救の奇跡－ドラガイト
aka Blue Synchro
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414002 - Adamacia Researcher --魔救の探索者
aka Red Human
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414004 - Adamacia Crysta - Leonite --魔救の奇石－レオナイト
aka Red Rock
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414007 - Adamacia Rise - Leonite --魔救の奇跡－レオナイト
aka Red Synchro
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414003 - Adamacia Analyzer --魔救の分析者
aka Green Human
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414005 - Adamacia Crysta - Raptite --魔救の奇石－ラプタイト
aka Green Rock
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414008 - Adamacia Rise - Raptite --魔救の奇跡－ラプタイト
aka Green Synchro
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414010 - Adamacia Laputite --アダマシア・ラピュタイト
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414011 - Adamacia Sign --魔救の息吹
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414012 - Adamacia Relieve --魔救の救砕
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414013 - Adamacia Resonance --魔救共振撃
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by AlphaKretin** [comment]
I have the "Green" monsters, Eerie has the "Blue" ones and CC has the "Red" ones. Backrow up for grabs

**Comment by ahtelel** [comment]
Doing Raputite

**Comment by LogicalNonsense2051** [comment]
Claiming Adamacia Sign.

**Comment by ahtelel** [comment]
Doing Resonance

**Comment by LogicalNonsense2051** [comment]
Adamacia Relieve.
