### ISSUE TITLE
IGAS Remaining cards

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#160]
## Ignition Assault - 101011XXX

Plunder Patroll: 0x23f

### 101011085 - Whitebeard, the Plunder Patroll Helm
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101011086 - Redbeard, the Plunder Patroll Matey
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101011087 - Plunder Patroll Brann
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101011088 - Plunder Patrollship Moerk
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101011089 - Blackbeard, the Plunder Patroll Captain
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101011090 - Plunder Patroll Shipyarrrd
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101011091 - Plunder Patroll Booty
- [x] Claimed
- [x] Scripted
- [x] Tested

### 1010110XX - [Nine Lives Cat](https://cdn.discordapp.com/attachments/372687218310905856/666991525196070912/unknown.png)
- [x] Claimed
- [x] Scripted
- [x] Tested

### 1010110XX - [Guard Ghost](https://cdn.discordapp.com/attachments/372687218310905856/666992047051505676/unknown.png)
- [x] Claimed
- [x] Scripted
- [x] Tested

### 1010110XX - [Anihhilator Archfiend](https://cdn.discordapp.com/attachments/372687218310905856/666993021111238656/unknown.png)

- [x] Claimed
- [x] Scripted
- [x] Tested

### 1010110XX - [Feedran, The Winds of Mischief](https://cdn.discordapp.com/attachments/372687218310905856/666993569474674728/unknown.png)

- [x] Claimed
- [x] Scripted
- [x] Tested

### 1010110XX - [Execution of Contract](https://cdn.discordapp.com/attachments/372687218310905856/666993666845310997/unknown.png)

- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by EerieCode** [comment]
I'll do the ShipYARRRd. 
...those names, I swear... -_-

**Comment by larry126** [comment]
Claim Xyz

**Comment by pyrQ** [comment]
I'll take the Synchro

**Comment by ahtelel** [comment]
Doing Whitebeard

**Comment by EerieCode** [comment]
I'll take the Booty then

**Comment by AlphaKretin** [comment]
Plunder Patroll Booty needs strings for "Do you want to take a monster?" and "Do you want to Special Summon it?"

**Comment by NaimSantos** [comment]
i'm taking Nine Lives Cat

**Comment by EerieCode** [comment]
I'll do Annihilator. ...finally something with a name that doesn't make me groan...

**Comment by NaimSantos** [comment]
I am taking Guard Ghost

**Comment by NaimSantos** [comment]
I am taking execution of contract

**Comment by NaimSantos** [comment]
scripting the dragon thing
