### ISSUE TITLE
VJump February Structure Deck R: Machiner's Command

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#166]
### 100310023 - Machina Reformation - JP NAME
- [x] Claimed
- [x] Scripted
- [ ] Tested
### 100310024 - Machina Defense Region - JP NAME
- [x] Claimed
- [x] Scripted
- [ ] Tested
### 100310034 - Machina Overdrive - JP NAME
- [x] Claimed
- [x] Scripted
- [ ] Tested
### 100310040 - Machina Possesstorage - JP NAME
- [x] Claimed
- [x] Scripted
- [ ] Tested

**Comment by EerieCode** [comment]
I'll do Machina Reformation

**Comment by lrhel** [comment]
Will do Defense Region

**Comment by lrhel** [comment]
will do Machina Possesstorage

**Comment by lrhel** [comment]
will do Overdrive

**Comment by kevinlul** [comment]
working on puzzles

**Comment by kevinlul** [comment]
puzzles PR'd
