### ISSUE TITLE
VJump February Secret Slayers

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#168]
## Deck Build Pack: Secret Slayers - 1004140XX
https://ygorganization.com/dreadofthegrave/
Eldlich: 0x241
Eldlixir: 0x242
Golden Land: 0x243
### 100414028 - Cursed El Dorlando - 呪われしエルドランド
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414029 - Eldlixir of Black Awakening - 黒き覚醒のエルドリクシル
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414030 - Eldlixir of White Fate - 白き宿命のエルドリクシル
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414031 - Eldlixir of Red Splatter - 紅き血染めのエルドリクシル
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414032 - Guardian of the Golden Land - 黄金郷のガーディアン
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414033 - Vaquero of the Golden Land - 黄金郷のワッケーロ
(Discrepancy from Org name based on Spanish speakers)
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414034 - Conquistador of the Golden Land - 黄金郷のコンキスタドール
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414035 - The Everglorious Golden Land - 永久に輝けし黄金郷
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414036 - El Dorado Adelantado - 黄金の征服王
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by AlphaKretin** [comment]
Dibs on Dark Elixir

**Comment by ahtelel** [comment]
Doing everglorious golden land

**Comment by AlphaKretin** [comment]
With one Eldlixir scripted, note that a lot of these archetypes are templated, which allows for copy-pasting. I'm going to hunt for Japanese names before I claim something else

**Comment by ahtelel** [comment]
Doing cursed el doland

**Comment by AlphaKretin** [comment]
I'll do White Fate

**Comment by kevinlul** [comment]
Puzzles might be complex for these because of relatedness, so multiple cards per puzzle?

**Comment by AlphaKretin** [comment]
For sure. Possibly worth evening making just the one puzzle, if there's room in the deck/STzone etc.

**Comment by AlphaKretin** [comment]
Doing red splatter

**Comment by AlphaKretin** [comment]
The trap monsters are as similar as the Eldlixirs, so whoever claims one should probably end up taking responsibility for all 3

**Comment by AlphaKretin** [comment]
I guess I'll do Adelantado

**Comment by NaimSantos** [comment]
I am taking all the remaining Continuous Golden Land cards
