### ISSUE TITLE
VJump February Sacred Beast Structure Deck

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#170]
## Structure Deck: Sacred Beasts of Chaos - 100338XXX
Raviel, Uria, Hamon IDs: 69890967,6007213,32491822
### 100338001 - Raviel, Lord of Phantasms - Shimmering Scraper - 幻魔皇ラビエル－天界蹂躙拳
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100338003 - Dark Calling Beast - 暗黒の招来神
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100338019 - Cerulean Skyfire - 失楽の霹靂
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100338034 - Hyper Blaze - ハイパーブレイズ
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by ahtelel** [comment]
Doing new Raviel

**Comment by AlphaKretin** [comment]
I'll do Dark Calling Beast
