### ISSUE TITLE
VJump February - Rise of the Duelist

### ISSUE THREAD

**Issue by EerieCode** [EerieCode/Percy-Alpha-Testing#171]
### 101101001 - Magic Knight Gaia --魔道騎士ガイア
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101002 - Cursed Dragon - Curse of Dragon --呪われし竜-カース・オブ・ドラゴン
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101003 - Howitzer Catapult Turtle --砲撃のカタパルト・タートル
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101004 - Soldier Gaia the Fierce Knight --暗黒騎士ガイアソルジャー
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101037 - Gaia the Dragonic Magic Knight --竜魔道騎士ガイア
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101049 - Rushing Gaia --走破するガイア
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101050 - Spiral Fusion --螺旋融合
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101068 - Spiral Discharge --螺旋砲撃
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101069 - Spiral Reborn --螺旋蘇生
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by EerieCode** [comment]
I'm doing the first 2 monsters, Cat is taking the Turtle

**Comment by AlphaKretin** [comment]
I'll do Gaia Soldier (I'd *like* to do the Fusion but CC did mention it in Discord)

**Comment by AlphaKretin** [comment]
I'll do the field

**Comment by NaimSantos** [comment]
Taking Spiral Discharge and Reborn
