### ISSUE TITLE
VJump February Rise of the Duelist One-Off Support Cards

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#172]
### 101101029 - Nemesys Keystone - ネメシス・キーストーン
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101036 - Megalith Phul - メガリス・フール
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101048 - Ancient Warriors Allied Generals - Shuanglong - 戦華盟将-双龍
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101059 - Magallanica, the Deep Sea City - 深海の都 マガラニカ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101060 - Ancient Warriors Saga - Southeast Wind - 戦華史略-東南之風
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101076 - Shaddoll Ruq - 影依の偽典
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by AlphaKretin** [comment]
I'll do Nemesys Keystone

**Comment by larry126** [comment]
Dib on the 2 Senka

**Comment by EerieCode** [comment]
I'll try to do Magallanica
