### ISSUE TITLE
VJump March DBSS

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#174]
## Deck Build Pack Secret Slayers - 1004140XX
https://ygorganization.com/underpressuresamplenumber1/
`Snowflower: 0x244`
### 100414014 - Snowflower Petal - 六花のひとひら
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414015 - Snowflower Sprite Prim - 六花精プリム
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414016 - Snowflower Sprite Cyclan - 六花精シクラン
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414017 - Snowflower Sprite Peony - 六花精ボタン
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414018 - Snowflower Sprite Erica - 六花精エリカ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414019 - Snowflower Sprite Snowdrop - 六花精スノードロップ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414020 - Snowflower Sprite Helleborus - 六花精ヘレボラス
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414021 - Snowflower Saint Kanzashi - 六花聖カンザシ
- [ ] Claimed
- [ ] Scripted
- [ ] Tested
### 100414023 - Stunning Snowflower - 六花絢爛
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414024 - Swirling Snowflowers - 六花の風花
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414025 - Silent Snowflower - 六花深々
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100414026 - Snowflower Sheet - 六花の薄氷
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by AlphaKretin** [comment]
Aht claimed petal, I claimed helleborus

**Comment by NaimSantos** [comment]
Taking Swirling Snowflowers, the continuous Spell

**Comment by ahtelel** [comment]
Doing Prim

**Comment by NaimSantos** [comment]
Taking Stunning Snowflower, the normal spell

**Comment by ahtelel** [comment]
Doing Botan

**Comment by NaimSantos** [comment]
Taking Silent Snowflower

**Comment by NaimSantos** [comment]
taking Snowflower Sheet

**Comment by LogicalNonsense2051** [comment]
Claiming Snowflower Sprite Snowdrop.

**Comment by pyrQ** [comment]
Claiming Cyclan
