### ISSUE TITLE
VJump March Sacred Beasts

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#175]
### 100338002 - Chaos Core - カオス・コア
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100338004 - Chaos Summoning Beast - 混沌の召喚神
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100338020 - Gate of the Seven Stars/Shadow Riders - 七精の解門
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100338035 - Awakened Sacred Beasts - 覚醒の三幻魔
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by AlphaKretin** [comment]
Dibs on the gate

**Comment by AlphaKretin** [comment]
pyrQ claims the beast

**Comment by AlphaKretin** [comment]
I'll do the SB trap too

**Comment by EerieCode** [comment]
I'll do Chaos Core then
