### ISSUE TITLE
VJump March ROTD Misc

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#176]
### 101101026 - Machina Reserbreak - マシンナーズ・リザーブレイク
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101027 - Strange Start Up Device Malefactor - 奇動装置メイルファクター
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101028 - Mathmech Dia - 斬機ダイア
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101066 - Heavenly Dragon Ring - 天幻の龍輪
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101077 - Dragonmaid Cleaning - ドラゴンメイドのお片付け
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by NaimSantos** [comment]
Taking Dragonmaid Clean-Up

**Comment by NaimSantos** [comment]
Taking Dragon Cycle of Celestial Illusions

**Comment by NaimSantos** [comment]
taking Unauthorized Device Malefactor
