### ISSUE TITLE
VJump March ROTD Noble Knights

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#177]
## Rise of the Duelist - 1011010XX
Note that the 『』 quotes *are* part of the JP name where they appear
### 101101012 - Flame Noble Knight Astolfo - 焔聖騎士-アストルフォ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101013 - Flame Noble Knight Ogier - 焔聖騎士-オジエ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101014 - Flame Noble Knight Olivier - 焔聖騎士-オリヴィエ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101015 - Flame Noble Knight Maugis - 焔聖騎士-モージ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101041 - Flame Noble Knight Leader Roland - 焔聖騎士導-ローラン
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101042 - Flame Noble Knight Emperor Charle - 焔聖騎士帝-シャルル
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101053 - Flame Noble Arms Durandal - 『焔聖剣-デュランダル』
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101054 - Flame Noble Arms Hauteclere - 『焔聖剣-オートクレール』
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101055 - Flame Noble Arms Joyeuse - 『焔聖剣-ジョワユーズ』
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101072 - Oliphant Horn - オリファンの角笛
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by AlphaKretin** [comment]
I've claimed Astolfo (transphobes get banned) and Durandal

**Comment by LogicalNonsense2051** [comment]
Claiming Flame Noble Knight Ogier and Flame Noble Knight Olivier.

**Comment by ClementLouis** [comment]
Claiming Emperor Charle and Vanguard Roland

**Comment by NaimSantos** [comment]
Taking Flame Noble Arms - Hauteclere

**Comment by NaimSantos** [comment]
Taking Flame Noble Arms Joyeuse

**Comment by NaimSantos** [comment]
Taking Olifant Horn
