### ISSUE TITLE
VJump March ROTD Merfae

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#178]
## Rise of the Duelist - 1011010XX
Melfie setcode: 0x242
### 101101016 - Merfae Rabbie - メルフィー・ラビィ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101017 - Merfae Fennie - メルフィー・フェニィ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101018 - Merfae Cathie - メルフィー・キャシィ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101019 - Merfae Puppie - メルフィー・パピィ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101020 - Merfae Ponie - メルフィー・ポニィ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101044 - Merfaes of the Forest - 森のメルフィーズ 
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101045 - Merfae Mommie - メルフィー・マミィ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101056 - Merfae Tag - メルフィーのおいかけっこ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101057 - Merfae Hide-and-Seek - メルフィーのかくれんぼ
- [x] Claimed
- [x] Scripted
- [x] Tested
### 101101073 - Merfae Time - メルフィータイム
- [x] Claimed
- [x] Scripted
- [x] Tested

Unrelated, but because it's otherwise unaddressed
### 100200180 - Cyberspace Princess Niangniang - 電脳堺姫－娘々
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by AlphaKretin** [comment]
Rabbie is a vanilla, I dib Fennie and Cathie, Larry dibs Puppie

**Comment by ahtelel** [comment]
Doing tag and hide and seek

**Comment by LogicalNonsense2051** [comment]
Taking "Cyberspace Princess Niangniang", although can't work on it until I've arrived home.

**Comment by ahtelel** [comment]
Doing Melfies of forest

**Comment by pyrQ** [comment]
Taking Ponie

**Comment by pyrQ** [comment]
Doing Mommie

**Comment by EerieCode** [comment]
I'll do Merfae Time
