### ISSUE TITLE
VJump March Duelists of Gloom

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#180]
### 100424001 - God Slime - 神・スライム
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100424017 - Meklord Emperor Wisel - Synchro Absorption - 機皇帝ワイゼル∞-S・アブソープション
- [x] Claimed
- [x] Scripted
- [x] Tested
### 100424034 - Cyber Energy Shock - 電脳エナジーショック
- [x] Claimed
- [x] Scripted
- [x] Tested

**Comment by AlphaKretin** [comment]
Larry claims slime, I claim Wisel

**Comment by LogicalNonsense2051** [comment]
I'll take the last one.
