### ISSUE TITLE
VJump - May 2018

### ISSUE THREAD

**Issue by EerieCode** [EerieCode/Percy-Alpha-Testing#2]
- [x] 100334041 - Shootingcode Talker
- [x] 100334042 - Elphase
- [x] 100334043 - Talkback Lancer
- [x] 100409002 - Blue-Eyes Solid Dragon
- [x] 100409003 - Bingo Machine GO! GO!
- [x] 100409012 - Cyber Eternity Dragon
- [x] 100409013 - Cyber Pharos
- [x] 100409014 - Cyberload Fusion
- [x] 100409023 - Blackwing Full Armored Master
- [x] 100409024 - Blackwing - Simoom the Poison Winds
- [x] 100409025 - Blackwing - Auster the South Wind
- [x] 100409034 - Starliege Photon Blast Dragon
- [x] 100409035 - Photon Vanisher
- [x] 100409038 - Photon Change
- [x] 100200150 - Predaplant Spider Orchid
- [x] 100200151 - Frightfur Meister

**Comment by ahtelel** [comment]
marked Blackwing cards
