### ISSUE TITLE
Guardragons 

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#26]
https://yu-gi-oh.jp/index.php?page=details&&id=403
https://ygorganization.com/dragonrulerfriends/
- [x] SAST-JP012 - Guardragon Eustia (vanilla) 
- [x] SAST-JP013 - Guardragon Garmides
- [x] SAST-JP014 - Guardragon Prominesis
- [x] SAST-JP015 - Guardragon Andrake
- [x] SAST-JP051 - Guardragon Erpy
- [x] SAST-JP052 - Guardragon Pisty
- [x] SAST-JP053- Guardragon Agarpain
- [x] SAST-JP061 - Guardragon Barrier
- [x] SAST-JP062 - World Legacy's Guardragon
- [x] SAST-JP072 - Guardragon Awakening
- [x] SAST-JP073 - Guardragon Corruption

**Comment by AlphaKretin** [comment]
I'm going to start not with a specific card, but a function to count link monsters pointing at zones, for the sake of the links

**Comment by EerieCode** [comment]
I'll do the Spells and Traps, if no one else is working on them

**Comment by AlphaKretin** [comment]
I guess I'll tackle the links, starting with the link 2. May as well make use of that function I wrote
