### ISSUE TITLE
Savage Strike

### ISSUE THREAD

**Issue by ClementLouis** [EerieCode/Percy-Alpha-Testing#30]
https://ygorganization.com/rondonumba9lifeofasavage/
- [x] SAST-JP001 Catche Eve L2
- [x] SAST-JP002 Cyberse Synchron
- [x] SAST-JP003 Salamangreat Wolvie
- [x] SAST-JP004 Salamangreat Parro
- [x] SAST-JP005 Salamangreat Foxer
- [x] SAST-JP020 Illusion Dragon Phantazmei
- [x] SAST-JP021 Orcust Knightmare
- [x] SAST-JP026 Fuuraibou
- [x] SAST-JP027 Rainbow Treasure Dragon
- [x] SAST-JP029 Sumiika
- [x] SAST-JP030 The Proud Beast
- [x] SAST-JP031 Extracaretops
- [x] SAST-JP032 Impcantation Chalisrhyme
- [x] SAST-JP043 Cyberse Integrator
- [x] SAST-JP044 Cyberse Widkid
- [x] SAST-JP045 Update Jammer
- [x] SAST-JP046 Detonate Deleter
- [x] SAST-JP047 Clock Lizard
- [x] SAST-JP065 Impcantation Celebrated Birth(?)
- [x] SAST-JP066 Unizong Tune
- [x] SAST-JP068 Edge of the Ring
- [x] SAST-JP069 Daitan Muteki (pun on daitanfuteki, “daredevilishness/audacity” and muteki, “invincible”)
- [x] SAST-JP070 Summon Over
- [x] SAST-JP076 Orcustrated Release 
- [x] SAST-JP080 Timewasting

**Comment by AlphaKretin** [comment]
Hella dibs on the Orcust stuff

**Comment by AndreOliveiraMendes** [comment]
is daitan muteki Boldly Invincible?

**Comment by AlphaKretin** [comment]
Yes @AndreOliveiraMendes , untranslated japanese name

**Comment by ClementLouis** [comment]
Eve Lv2, SG Parro/Foxer, Clock Lizard, update Jammer, Detonate Deleter should be close if not iddentical to their anime version

**Comment by ClementLouis** [comment]
dealing with Cat Eve L2

**Comment by ahtelel** [comment]
@LogicalNonsense2051 Check the cards you want to do and comment here BEFORE you do the cards, please, thanks

**Comment by AlphaKretin** [comment]
I guess I'll try my hand at Extracaretops

**Comment by ahtelel** [comment]
proud beast

**Comment by LogicalNonsense2051** [comment]
I'll work on Cyberse Widkid then.

**Comment by LogicalNonsense2051** [comment]
Planning to do Impcantation Chalislime now.

**Comment by AlphaKretin** [comment]
Sorry for the confusion, wound up finding the time

**Comment by EerieCode** [comment]
I'm planning on doing Summon Over and Illusion Dragon Phantazmei

**Comment by AlphaKretin** [comment]
Guess I'll do Sumiika

**Comment by EerieCode** [comment]
I'll do the Impcantation Ritual Spell then, it's still marked as to be done

**Comment by AlphaKretin** [comment]
That's all cards claimed - when @LogicalNonsense2051 uploads the two cards they last claimed, they should all have been done and this issue can be closed

**Comment by LogicalNonsense2051** [comment]
Late as ever, but finally completed them.

**Comment by larry126** [comment]
All uploaded
