### ISSUE TITLE
Savage Strike Tested

### ISSUE THREAD

**Issue by larry126** [EerieCode/Percy-Alpha-Testing#34]
Tick if the card is tested
- [x] SAST-JP001 Catche Eve L2
- [x] SAST-JP002 Cyberse Synchron
- [x] SAST-JP003 Salamangreat Wolvie
- [x] SAST-JP004 Salamangreat Parro
- [x] SAST-JP005 Salamangreat Foxer
- [x] SAST-JP020 Illusion Dragon Phantazmei
- [x] SAST-JP021 Orcust Knightmare
- [x] SAST-JP026 Skyward Sealing Sage
- [x] SAST-JP027 Rainbow Treasure Dragon
- [x] SAST-JP029 Sumiika
- [x] SAST-JP030 The Proud Beast
- [x] SAST-JP031 Extracaretops
- [x] SAST-JP032 Impcantation Chalisrhyme
- [x] SAST-JP043 Cyberse Integrator
- [x] SAST-JP044 Cyberse Widkid
- [x] SAST-JP045 Update Jammer
- [x] SAST-JP046 Detonate Deleter
- [x] SAST-JP047 Clock Lizard (**works incorrectly** under specific scenarios, see comments)
- [x] SAST-JP065 Impcantation Celebrated Birth(?)
- [x] SAST-JP066 Unizong Tune
- [x] SAST-JP068 On the Edge of the Ring
- [x] SAST-JP069 Daitan Muteki/Refuge in Audacity/Boldly Invencible
- [x] SAST-JP070 Summon Over
- [x] SAST-JP076 Orcustrated Release 
- [x] SAST-JP080 Timewasting

**Comment by larry126** [comment]
@NaimSantos I am working on SGs atm

**Comment by larry126** [comment]
Clock Lizard may need ruling confirmation

**Comment by NaimSantos** [comment]
For the 1: if you cannot perform a Fusion Summon (e.g. Dimensional Barrier) you cannot activate the the effect.
For the 2: we can compare the japanese text with similar cards that affects cards currently on the field only (eg. Performapal Lebellman's pendulum effect)
By the time i write this message , Yugipedia didnt have the text in japanese to be copied (only the picture).

**Comment by larry126** [comment]
> For the 1: if you cannot perform a Fusion Summon (e.g. Dimensional Barrier) you cannot activate the the effect.
> For the 2: we can compare the japanese text with similar cards that affects cards currently on the field only (eg. Performapal Lebellman's pendulum effect)
> By the time i write this message , Yugipedia didnt have the text in japanese to be copied (only the picture).

Well, then this card is doomed because we don't have a way to check for the scenario I mentioned in 1. As for 2, I checked the Japanese text, and I am not convinced which way it is.

**Comment by NaimSantos** [comment]
> Well, then this card is doomed because we don't have a way to check for the scenario I mentioned in 1. 
As always, blamekonami

**Comment by EerieCode** [comment]
What if we assume the location to be LOCATION_EXTRA, and then we check if the card can be Fusion Summoned?

**Comment by NaimSantos** [comment]
Results of a few tests:
1-I have ABC and its parts (  A, B and C) in the gy. I can activate the effect and target it, shuffling it into the ED, which i should not be able to, as ABC cannot be fusion summoned
2-Yang Zing Creation is face-up on the field: i can activate the effect and target First of the Dragons (shuffled to the ED), which i should not as Yang Zing Creation prevents summons, excpt Yang Zings

**Comment by AndreOliveiraMendes** [comment]
so basicaly, ASSUME_LOCATION ~OMEGALOL~

**Comment by NaimSantos** [comment]
The 3 last cards were tested and didnt show any major bugs in my tests.
