### ISSUE TITLE
VJump October [scripts]

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#38]
https://yu-gi-oh.jp/index.php?page=details&&id=404
https://ygorganization.com/cyberbladerisonabusinesstrip/

- [x] DP21-JP012 - Cyber Angel Izuna (100411012)
- [x] DP21-JP013 - Cyber Egg Angel (100411013)
- [x] DP21-JP014 - The Merciful Machine Angel (100411014)
- [x] DP21-JP015 - Machine Angel Manifestation (100411015)

https://yu-gi-oh.jp/index.php?page=details&&id=405
https://ygorganization.com/pitchblackflowerblooms/

- [x] DP21-JP023 - Garden Rose Maiden
- [x] DP21-JP024 - Dark Rose Fairy
- [x] DP21-JP025 - Red Rose Dragon
- [x] DP21-JP026 - Frozen Roars
- [x] DP21-JP027 - Blooming Rose

https://yu-gi-oh.jp/index.php?page=details&&id=406
https://ygorganization.com/choochookaboom/

- [x] DP21-JP034 - Super Dreadnought Railway Cannon Juggernaut Reeve
- [x] DP21-JP035 - Bullet Express Bullet Liner
- [x] DP21-JP036 - Berserk Railway Flying Pegasus
- [x] DP21-JP037 - Urgent Schedule

Link Vrains Pack 2 
https://ygorganization.com/link-vrains-pack-2-news/
- [x] 100235001  - Warrior of Chaos - Black Luster Soldier     混沌の戦士 カオス・ソルジャー
- [x] 100235011 - Thundermech Thunder Dragon   轟雷機龍-サンダー・ドラゴン
- [x] 100235016 - Celestial Knight Lord Parshath    天空神騎士ロードパーシアス
- [x] 100235026 - Alien Soldier Mighty/Frame    エーリアン・ソルジャー M/フレーム
- [x] 100235031 - Dragunity Romulus    ドラグニティナイト - ロムルス
- [x] 100235066 - D/D/D Abyss King Bilgameth      DDD深淵王ビルガメス

https://yu-gi-oh.jp/index.php?page=details&&id=411

- [x] 100335052 - Salamangreat Veil Lynx     転生炎獣ベイルリンクス

**Comment by AlphaKretin** [comment]
I'll start working on Izuna

**Comment by LogicalNonsense2051** [comment]
I'll work on...whatever else is left and has translations as well.

**Comment by AndreOliveiraMendes** [comment]
i think i'll do the egg one

**Comment by AndreOliveiraMendes** [comment]
idk what it id xD

**Comment by AndreOliveiraMendes** [comment]
100411013 right?

**Comment by LogicalNonsense2051** [comment]
Is it just me, or is the V-Jump section of Percy-Testing-Alpha gone?

**Comment by AndreOliveiraMendes** [comment]
yes, it you, the special snowfloke... jooking
well, it had some cleanup, but you can create a folder if necessary

**Comment by AlphaKretin** [comment]
That was for the actual set VJMP, for promos, of which the latest one was uploaded a while ago. 
This is news from V-Jump, but for cards in various sets, listed by the names.

**Comment by ahtelel** [comment]
ill finish up with teh last card thxz

**Comment by EerieCode** [comment]
I'll do Garden Rose Maiden

**Comment by AlphaKretin** [comment]
I guess I'll do dark rose fairy

**Comment by EerieCode** [comment]
I'm willing to do Juggernaut Reeve too

**Comment by AlphaKretin** [comment]
I'll do the train stuff, starting with pegasus then maybe bullet liner

**Comment by AlphaKretin** [comment]
I gotta go, so I won't do Liner after all (at least right now, might re-claim it in the future)

**Comment by AlphaKretin** [comment]
Time to finally finish this off (until we get LVP news tomorrow????) with Urgent Schedule...

**Comment by larry126** [comment]
All made

**Comment by AndreOliveiraMendes** [comment]
i think i'll do Warrior of Chaos - Black Luster Soldier

**Comment by AlphaKretin** [comment]
I have an idea for Thundermech/Titan, so I'll try that

**Comment by LogicalNonsense2051** [comment]
I'll look into "D/D/D Abyss King Bilgameth" once I am free.

**Comment by EerieCode** [comment]
I'll do Parshath then. Maybe the Alien too, if I can

**Comment by ahtelel** [comment]
Issue updated with OCG names; please add these to the first line in their respective scripts

**Comment by AlphaKretin** [comment]
Sorry, unreserving the Thunder Dragon. I sat down and realised I'm too tired to focus on a script.

**Comment by EerieCode** [comment]
I'm also unreserving the Alien, I won't be able to script it before going to work. I'll see if I can help some more later

**Comment by LogicalNonsense2051** [comment]
Alright, I will take responsibility over "Alien Soldier Mighty/Frame" then.

**Comment by EerieCode** [comment]
Alright. For Thunder Dragon, we've already figured out a solution for its first effect, so, if Alpha is still tired later, I'll try to script it.

**Comment by EerieCode** [comment]
Also, I'm doing the new Salamangreat. For future information, since the Structure Deck also has a booster pack included, the numeration of all cards with code SD35-JPP-- starts from 50: this way, it won't intersect the main Deck or eventual Tokens
