### ISSUE TITLE
VJump October [test] 

### ISSUE THREAD

**Issue by NaimSantos** [EerieCode/Percy-Alpha-Testing#41]
Test the cards for script errors and bugs with basic scenarios then fix it, if possible. Check if the card was tested. Cards tested are usually uploaded first

- [x] DP21-JP012 - Cyber Angel Izana
- [x] DP21-JP013 - Cyber Egg Angel
- [x] DP21-JP014 - The Merciful Machine Angel
- [x] DP21-JP015 - Machine Angel Manifestation
- [x] DP21-JP023 - Garden Rose Maiden
- [x] DP21-JP024 - Dark Rose Fairy
- [x] DP21-JP026 - Frozen Roars
- [x] DP21-JP027 - Blooming Rose
- [x] DP21-JP034 - Super Dreadnought Railway Cannon Juggernaut Reeve
- [x] DP21-JP035 - Speedy Express Bullet Liner
- [x] DP21-JP036 - Runaway Railcar Flying Pegasus
- [x] DP21-JP037 - Urgent Schedule

**Comment by NaimSantos** [comment]
Frozen Roar:
1-Do I have to be able to draw to activate it, while i control only plants (the draw is in the EP)?
2-What happens if i send a plant monster that currently is non-Plant (DNA Surgery, Zombie World, etc)? Which effect do i apply?

**Comment by NaimSantos** [comment]
Last issue left: Berserk Railway Flying Pegasus is currently stoping ALL monsters from attacking.

**Comment by AlphaKretin** [comment]
From Dyxel's testing: Urgent Schedule can summon two monsters with the same level, as well as night express knight

**Comment by AlphaKretin** [comment]
Fixed now, was a wrong function name, dealing with other issues

**Comment by AlphaKretin** [comment]
All tested
