### ISSUE TITLE
Link Vrains Pack 2 [tests]

### ISSUE THREAD

**Issue by NaimSantos** [EerieCode/Percy-Alpha-Testing#44]
Test the cards for script errors and bugs with basic scenarios then fix it, if possible. Check if the card was tested. Cards tested are usually uploaded first

Source: https://ygorganization.com/link-vrains-pack-2-news/

 - [x] 100235001 - Warrior of Chaos - Black Luster Soldier 混沌の戦士 カオス・ソルジャー
 - [x]  100235011 - Thundermech Thunder Dragon 轟雷機龍-サンダー・ドラゴン
 - [x]  100235016 - Celestial Knight Lord Parshath 天空神騎士ロードパーシアス
 - [x]  100235026 - Alien Soldier Mighty/Frame エーリアン・ソルジャー M/フレーム
 - [x]  100235031 - Dragunity Romulus ドラグニティナイト - ロムルス
 - [x]   100235066 - D/D/D Abyss King Bilgameth DDD深淵王ビルガメス

**Comment by AlphaKretin** [comment]
I'll help test out the Thunder Dragon once I finish some busywork - it could use multiple eyes on it though

**Comment by AlphaKretin** [comment]
Goliath is tested but still has issues, leaving it unchecked until resolved. See commit 5950609
