### ISSUE TITLE
SOFU Card left to do

### ISSUE THREAD

**Issue by ClementLouis** [EerieCode/Percy-Alpha-Testing#5]
- [x] 101006017 - "World Legacy - "World Scepter""
- [x] 101006032 - "Two-Man Salesmen"
- [x] 101006057 - "Orphegel Babel"
- [x] 101006058 - "Orphegel Prime"
- [x] 101006059 - "Orphegel Einsatz"
- [x] 101006063 - "Abyssal Judge"
- [x] 101006064 - "Concentrate"
- [x] 101006066 - "Parallel Panzer"
- [x] 101006074 - "Krawler Palladion"
- [x] 101006075 - "Necro Fusion"
- [x] 101006079 - "Breaking Point of the Normal"

**Comment by ahtelel** [comment]
Will close issue after someone else double check

**Comment by NaimSantos** [comment]
Combining these with Fluo's, all cards are scripted now. Just need tests.
