### ISSUE TITLE
VJump November

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#53]
It seems to actually be happening today, more than just one reveal.
https://ygorganization.com/mylittlemiragestallionsoulburnerismagic/
- [x] SD35-JP001 Salamangrate Racoon / Salamangreat Racoon
https://yugipedia.com/wiki/Salamangreat_Raccoon
- [x] SD35-JP003 SD35-JP003 Salamangreat Gazelle / Salamangreat Gazelle
https://yugipedia.com/wiki/Salamangreat_Gazelle
- [x] SD35-JP004 Salamangrate Spinny / Salamangreat Spinny
https://yugipedia.com/wiki/Salamangreat_Spinny
- [x] SD35-JP005 Salamangrate Fowl / Salamangreat Fowl
https://yugipedia.com/wiki/Salamangreat_Fowl
- [x] SD35-JPP01 Salamangrate Mirage Stallio / Salamangreat Mirage Stallio(n)
https://yugipedia.com/wiki/Salamangreat_Mirage_Stallio
- [x] SD35-JP023 Salamangrate Circle / Salamangreat Circle
https://yugipedia.com/wiki/Salamangreat_Circle

https://ygorganization.com/farbeyondtheinfernalstars/
- [x] 18SP-JP401 Daemon no Chouetsu / Exceeds Skull Archfiend

https://yu-gi-oh.jp/index.php?page=details&&id=438 translations incoming
- [x] Magician of Chaos (Eerie)
- [x] E HERO Grandman
- [x] Signal Warrior
- [x] Onomautopia
- [x] Odd-Eyes Advance Dragon (Eerie)
- [x] Backup Supervisor

https://yu-gi-oh.jp/index.php?page=details&&id=439
- [x] Salamangreat Al'lumiraj
- [x] Rose Bell of Revelation
- [x] Synchro Transcend
- [x] Memories of Hope
- [x] Enma's Judgement

**Comment by AlphaKretin** [comment]
Eerie's reserved the latter two Salamangoobers and I've already uploaded the Skull

**Comment by AlphaKretin** [comment]
Alright, I'll do Racoon to finish things off

**Comment by AlphaKretin** [comment]
lol ofc the second i give up

**Comment by LogicalNonsense2051** [comment]
Dibs on Onomautopia.

**Comment by AlphaKretin** [comment]
KK - Eerie's claimed Odd-Eyes and the Link, and I'm claiming the Fusion and Synchro

**Comment by EerieCode** [comment]
Now that I've seen the effects, I think I'll replace my claim on Supervisor with the Ritual, I find it more interesting. I'll do Magician of Chaos and Odd-Eyes Advance Dragon.

**Comment by LogicalNonsense2051** [comment]
Unless someone else is working on Backup Supervisor, I'll get started on it.

**Comment by AlphaKretin** [comment]
I don't think anyone is

**Comment by ahtelel** [comment]
Rose Bell is done

**Comment by ahtelel** [comment]
ONE MORE CARD UP FOR GRABS
