### ISSUE TITLE
Link Vrains Pack 2

### ISSUE THREAD

**Issue by EerieCode** [EerieCode/Percy-Alpha-Testing#62]
- [x] 036: Scrap Wyvern
- [x] 056: Brotherhood of the Fire Fist - Eagle
- [x] 061: Traptrix Sera
- [x] 071: Raidraptor - Wise Strix
- [x] 086: PSY-Framelord Lambda
- [x] 091: Comdemned Darklord

**Comment by NaimSantos** [comment]
I'll script the scrap link

**Comment by EerieCode** [comment]
I'll do the Fire Fist then

**Comment by ahtelel** [comment]
I'll close the damn thing
