### ISSUE TITLE
Bug test LVP2 - 17 Nov

### ISSUE THREAD

**Issue by NaimSantos** [EerieCode/Percy-Alpha-Testing#64]
Check what was tested and works without major issues. Leave coments for bugs you found but couldn't fix
- [x] 036: Scrap Wyvern
- [x] 056: Brotherhood of the Fire Fist - Eagle
- [x] 061: Traptrix Sera
- [x] 071: Raidraptor - Wise Strix
- [x] 086: PSY-Framelord Lambda
- [x] 091: Comdemned Darklord

**Comment by EerieCode** [comment]
Time to close this!
