### ISSUE TITLE
December 2018 [Scripts]

### ISSUE THREAD

**Issue by EerieCode** [EerieCode/Percy-Alpha-Testing#69]
Premium Pack 2019:
Cards to script
- [x] Mighty Flame Swordsman 001
- [x] Ojama Emperor 002
- [x] Superheavy Samurai Scarecrow 005
- [x] Speedroid Marble Machine 007
- [x] Speedroid Hexasaucer 008
- [x] Performapal Kuribohrder 009
- [X] Dark Anthelion Dragon 010
- [x] Starving Venemy Lethal Dose Dragon 011
- [x] Phantasm Emperor Trilojig 013
- [x] Number XX: Dark Utopic Infinity 014
----
DarkNeostorm [DANE]
- [x] Altergeist Fifionerag
- [x] Dinowrestler Chimera T Wrextle
- [x] Salamangreat Recurrence
- [x] Firewall Exceed Dragon
- [x] Astroknightmare Idlee
- [x] Guardragon of the World Legacy Merodark
- [x] Deus X-Krawler
- [x] Guidance of the World Legacy
- [x] Super Quantal White Layer
- [x] Super Quant Request Alphan Call
- [x] Super Quant Unification - Magna Formation
- [x] Fusion Destiny
- [x] Destiny HERO Drawguy
- [x] Destiny HERO Dominator
- [x] Xtra HERO Cross Guy
- [x] D - Tactics
- [x] Icicle Mayakashi - Yuki Musume
- [x] Magical Musket - Bloody Crown
- [x] The Weather Rainbow Canvas
- [x] Philo, Messenger Fur Hire
- [x] Chain Hole

**Comment by NaimSantos** [comment]
Adding also this check list for cards that have been **tested**
- [ ] Mighty Flame Swordsman 001
- [ ] Ojama Emperor 002
- [ ] Superheavy Samurai Scarecrow 005
- [ ] Speedroid Marble Machine 007
- [ ] Speedroid Hexasaucer 008
- [ ] Performapal Kuribohrder 009
- [ ] Dark Anthelion Dragon 010
- [ ] Starving Venemy Lethal Dose Dragon 011
- [ ] Phantasm Emperor Trilojig 013
- [ ] Number XX: Dark Utopic Infinity 014

**Comment by ahtelel** [comment]
Please mention anything you're working on here

**Comment by ahtelel** [comment]
Will do World Legacy Burgeoning

**Comment by NaimSantos** [comment]
I can take the altergeist :D

**Comment by EerieCode** [comment]
I'll do the Guardragon then

**Comment by NaimSantos** [comment]
I'll do Dinowrestler Chimera T Wrextle

**Comment by EerieCode** [comment]
I'll do Dominator

**Comment by ahtelel** [comment]
Doing d tactics next

**Comment by ahtelel** [comment]
Passing over d tactics to anyone interested, stuff happened

**Comment by ahtelel** [comment]
redibs on d tactics , will work on it in 1 hour hopefully

**Comment by LogicalNonsense2051** [comment]
Planning to work on the remaining Super Quant cards.

**Comment by EerieCode** [comment]
All cards have been done. Good job, everyone!
