### ISSUE TITLE
DANE Cards from late December [SCRIPTS]

### ISSUE THREAD

**Issue by NaimSantos** [EerieCode/Percy-Alpha-Testing#72]
Check this as you script the cards. Leave coments if you are planning to scrip any
- [x] Salamangreat Fennec  - 1010080**03**
- [x] Dinowrestler Coelasilat - 1010080**07**
- [x] Psi-Reflector - 1010080**10**
- [x] Neo Flamvell Lady - 1010080**14**
- [x] Creator of the Impcantations - Crealter - 1010080**29**
- [x] World Chalice Guardragon Almarduk - 1010080**32**
- [x] Altergeist Dragvirion - 1010080**33**
- [x] Dinowrestler Giga Spinosavate - 1010080**34**
- [x] Super Quantal Mech Beast Luster Rex  - 1010080**37**
- [x] Cyberse Reminder - 1010080**40**
- [x] Dillingerous Dragon - 1010080**41**
- [x] Gouki the Blade Ogre - 1010080**43**
- [x] Gouki the Solid Ogre - 1010080**44**
- [x] Mayakashi Memorial - 1010080**57**
- [x] Cloudian Aerosol - 1010080**58**
- [x] Altergeist Haunted Rock - 1010080**68**
- [x] World Divine Gear Demiurgear
- [x] True Super Quantal Mech King Blaster Magna - 1010080**46**
- [x] Chaos Betrayer
- [x] Manhunt - 1010080**78**

**Comment by EerieCode** [comment]
I'm doing Blaster Magna ATM
