### ISSUE TITLE
DANE Cards from late December [TEST]

### ISSUE THREAD

**Issue by NaimSantos** [EerieCode/Percy-Alpha-Testing#73]
Check these as you test the cards. Leave coments with important notes
- [x] Salamangreat Fennec  - 1010080**03**
- [x] Dinowrestler Coelasilat - 1010080**07**
- [x] Psi-Reflector - 1010080**10**
- [x] Neo Flamvell Lady - 1010080**14**
- [x] Creator of the Impcantations - Crealter - 1010080**29**
- [x] Altergeist Dragvirion - 1010080**33**
- [x] Dinowrestler Giga Spinosavate - 1010080**34**
- [x] Super Quantal Mech Beast Luster Rex  - 1010080**37**
- [x] Cyberse Reminder - 1010080**40**
- [x] Dillingerous Dragon - 1010080**41**
- [x] Gouki the Blade Ogre - 1010080**43**
- [x] Gouki the Solid Ogre - 1010080**44**
- [x] Mayakashi Memorial - 1010080**57**
- [x] Cloudian Aerosol - 1010080**58**
- [x] Altergeist Haunted Rock - 1010080**68**
- [x] World Chalice Guardragon Almarduk - 1010080**32**
- [x] World Regalia Demiurgear - 1010080**48**
- [x] True Super Quantal Mech King Blaster Magna - 1010080**46**
- [x] Chaos Betrayer
- [x] Manhunt - 1010080**78**

**Comment by NaimSantos** [comment]
Altergeist Haunted Rock can be activated the turn is set, not only if set by an Altergeist card, which is wrong

**Comment by AlphaKretin** [comment]
Link Material restriction on Dinowrestler Coelasilat - 101008007 does not work

**Comment by AlphaKretin** [comment]
Can't activate Psi-Reflector - 101008010's second effect

**Comment by AlphaKretin** [comment]
Can't activate Creator of the Impcantations - Crealter - 101008029's effect in the hand

**Comment by AlphaKretin** [comment]
Gouki the Solid Ogre - 101008044's protection seems not to work
