### ISSUE TITLE
Missing DANE Cards [Script]

### ISSUE THREAD

**Issue by NaimSantos** [EerieCode/Percy-Alpha-Testing#77]
Add the name of the cards as they are revealed. Check if you have already scripted and uploaded the script. Comment if you plan to take any, and mention which one(s).  Cards with a "*" are not in the cdb yet.

- [x] 101008006 - Dinowrestler Eskrimamenchi **[Tested]** **[ADDED]**
- [x] 101008008 - Dinowrestler Martial Anga **(same as anime)** **[ADDED]**
- [x] 101008011 - Assault Sniper **[Tested]** **[ADDED]**
- [x] 101008022 - Loud Cloud, the Disturbance-Causing-Noisy-Serpent  **[Tested]** **[ADDED]**
- [x] 101008023 - Xyz Slidolphin **[Tested]** **[ADDED]**
- [x] 101008025 - Null Nun & Blooming Dogwood **[Tested]** **[ADDED]**
- [x] 101008026 - Handy Gallop **[Tested]** **[ADDED]**
- [x] 101008028 - Low Cupit **[Tested]** **[ADDED]**
- [x] 101008038 - Sheorcust Dingirsu **[Tested]** **[ADDED]**
- [x] 101008047 - Mekk-Knight Crusadia Astram **[Tested]** **[ADDED]**
- [x] 101008049 - ????? Puzzomino **[untested]**
- [x] 101008053 - Tyrant Dino Fusion **[Tested]** **[ADDED]**
- [x] 101008060 - Guardragon Incarnation **[Tested]** **[ADDED]**
- [x] 101008061 - Crusadia Testament **[Tested]** **[ADDED]**
- [x] 101008063 - Lost Dragon's Strain **[Tested]** **[ADDED]**
- [x] 101008064 - Spellore Cave **[not in the cdb either]**
- [x] 101008065 - Mortschlag **[Tested]** **[ADDED]**
- [x] 101008066 - Stand In **[Tested]** **[ADDED]**
- [x] 101008067 - Creature Disconnection  **[Tested]** **[ADDED]**
- [x] 101008074 - Orcustrated Climax  **[Tested]** **[ADDED]**
- [x] 101008075 - World Legacy Annihilation **[Tested]**
- [x] 101008076 - World Legacy Finality **[Tested]**

**Comment by AlphaKretin** [comment]
I have dibs on Dingirsu, have since the picture was revealed. I can do Astram too if it's not done when I can, but I don't mind as much.

**Comment by AndreOliveiraMendes** [comment]
i think im doing Mekk-Knight Crusadia Astram probaly.

**Comment by AlphaKretin** [comment]
Dibs on Orcustrated Climax

**Comment by EerieCode** [comment]
I think I can do the 2 World Legacy Traps.

**Comment by AlphaKretin** [comment]
Working on Assault Sniper

**Comment by ahtelel** [comment]
doing low cupid

**Comment by ahtelel** [comment]
doing loud cloud

**Comment by AlphaKretin** [comment]
I guess I'll do Puzzomino

**Comment by NaimSantos** [comment]
I will script Mortschlag

**Comment by EerieCode** [comment]
I'll do Spellore Cave, then

**Comment by EerieCode** [comment]
Script complete! Should we close this issue and open one for testing?

**Comment by AlphaKretin** [comment]
DANE is official now there's no way this is still needed
