### ISSUE TITLE
VJump Jan 2019

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#78]
## 20th Anniversary Legend Collection - 1002361XX
- [x] 100236100 - Blue-Eyes Alternative Ultimate Dragon
- [x] 100236101 - Magician of Black Chaos MAX
- [x] 100236102 - Exodia, Master of The Guard
- [x] 100236103 - Palladium Oracle Mana
- [x] 100236104 - Red-Eyes Alternative Black Dragon
- [x] 100236105 - Neo Kaiser Glider
- [x] 100236106 - Malefic Divide (has anime script you can modify)
- [x] 100236118 - Cubic Omen
- [x] 100236114 - Cubic Ascension

## VJump Promotional Card - 100200XXX
- [x] 100200158 - Hi-Speedroid Kitedrake

## Deck Build Pack: Infinity Chasers - 100412XXX
- [x] 100412007 - Infinite Ignition Leverstorm **[tested, needs a second opinion on the attaching effect]**
- [x] 100412016 - Witchcraft Schmitta **[tested]**
- [x] 100412028 - Medusa, Watcher of the Evil Eye
- [x] 100412030 - Basilius, Retainer of the Evil Eye
- [x] 100412033 - Pareidolia, Domain of the Evil Eye (呪眼領閾-パレイドリア-)
- [x] 100412034 - Forbidden Awakening of the Evil Eye
- [x] 100412035 - Curse of the Evil Eye
- [x] 100412036 - Watchful Rule of the Evil Eye (静冠の呪眼)
- [x] 100412037 - Jealous Disruption of the Evil Eye (妬絶の呪眼)
- [x] 100412038 - Death Control of the Evil Eye (死配の呪眼)
- [x] 100412039 - Sentence of the Evil Eye (断罪の呪眼)

## 20th Anniversary Secret Rare Challenge - 1002460XX
- [x] 100246006 - Infinite Ignition Goliath (無限起動 ゴライアス)

## Structure Deck R: Lord of Magician - 100308XXX
- [x] Daybreaker the Splendid Magical Knight (魔導耀士 デイブレイカー)
- [x] Endymion, the Master Magician of Creation (創聖魔導王 エンディミオン)

**Comment by AlphaKretin** [comment]
I'll try my hand at Divine Protector Exodia

**Comment by AlphaKretin** [comment]
I guess I'll do Kaiser Glider?

**Comment by AlphaKretin** [comment]
i'll divide

**Comment by EerieCode** [comment]
I can try to do Max then

**Comment by AlphaKretin** [comment]
I'll do kitedrake

**Comment by AlphaKretin** [comment]
I'll work on Basilius

**Comment by AlphaKretin** [comment]
Medusa now

**Comment by AlphaKretin** [comment]
wails

**Comment by AlphaKretin** [comment]
disaster

**Comment by NaimSantos** [comment]
I will do Witchcraft Schmitta

**Comment by NaimSantos** [comment]
I will script Infinite Ignition Leverstorm

**Comment by AlphaKretin** [comment]
Someone on PC needs to add the two new cards, but I dibs Daybreaker and Eerie tentatively dibs Endimyon

**Comment by NaimSantos** [comment]
I will script Sentence of the Evil Eye

**Comment by ClementLouis** [comment]
Taking the Infinite ignition link since apparently nobody is doing it
