### ISSUE TITLE
Missing DBIC cards [Scripts]

### ISSUE THREAD

**Issue by NaimSantos** [EerieCode/Percy-Alpha-Testing#84]
Release date: February 23, 2019.
Add the missing information and script the following cards as they are revealed, then check the box; comment if you plan to take any of the cards.

- [x] 100412001 - Infinite Ignition Harverster - 無限起動ハーヴェスター
- [x] 100412004 - Infinite Ignition Dragshovel -  無限起動ドラグショベル
- [x] 100412005 - Infinite Ignition Trencher - 無限起動トレンチャー
- [x] 100412006 - Infinite Ignition Scraper - 無限起動スクレイパー
- [x] 100412012 - Outrigger Expand  - 超接地展開
- [x] 100412013 - Spin Turn - 超信地旋回
- [x] 100412014 - Witchcraft Potorie  - ウィッチクラフト・ポトリー
- [x] 100412015 - Witchcraft Pittole  - ウィッチクラフト・ピットレ
- [x] 100412017 - Witchcraft Edel  - ウィッチクラフト・エーデル
- [x] 100412018 - Witchcraft Heine  - ウィッチクラフト・ハイネ
- [x] 100412020 - Witchcraft Creation  - ウィッチクラフト・クリエイション
- [x] 100412021 - Witchcraft Sabotage  - ウィッチクラフト・サボタージュ
- [x] 100412022 - Witchcraft Collaboration  - ウィッチクラフト・コラボレーション
- [x] 100412023 - Witchcraft Draping  - ウィッチクラフト・ドレーピング
- [x] 100412024 - Witchcraft Bystreet  - ウィッチクラフト・バイストリート
- [x] 100412025 - Witchcraft Scroll  - ウィッチクラフト・スクロール
- [x] 100412026 - Witchcraft Masterpiece  - ウィッチクラフト・マスターピース

**Comment by AlphaKretin** [comment]
I have a prototype script for Eidel

**Comment by AlphaKretin** [comment]
Hold the phone on Hyne, one of the cards needs hardcoding in everything that does a discard. Ironically it doesn't need anything fancy itself so I'll script it, Scroll, instead.

**Comment by AlphaKretin** [comment]
never mind on that either multiple cards do it so we need to decide on the code. not dibsing anything until we know everything

**Comment by AlphaKretin** [comment]
In lieu of a specific card, I wrote the code for spells recurring themselves to be re-used
```lua
--Witchcraft Spell
local s,id=GetID()
function s.initial_effect(c)
    local e2=Effect.CreateEffect(c)
    e2:SetCategory(CATEGORY_TOHAND+CATEGORY_LEAVE_GRAVE)
    e2:SetDescription(aux.Stringid(id,1))
    e2:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_O)
    e2:SetCode(EVENT_PHASE+PHASE_END)
    e2:SetRange(LOCATION_GRAVE)
    e2:SetCountLimit(1,id+100)
    e2:SetCondition(s.thcon)
    e2:SetTarget(s.thtg)
    e2:SetOperation(s.thop)
    c:RegisterEffect(e2)
end
function s.thcon(e,tp,eg,ep,ev,re,r,rp)
    return Duel.IsExistingMatchingCard(aux.FilterFaceupFunction(Card.IsSetCard,0x228),tp,LOCATION_MZONE,0,1,nil)
end
function s.thtg(e,tp,eg,ep,ev,re,r,rp,chk)
    local c=e:GetHandler()
    if chk==0 then return c:IsAbleToHand() end
    Duel.SetOperationInfo(0,CATEGORY_TOHAND,c,1,tp,LOCATION_GRAVE)
end
function s.thop(e,tp,eg,ep,ev,re,r,rp,chk)
    local c=e:GetHandler()
    if c:IsRelateToEffect(e) then
        Duel.SendtoHand(c,tp,REASON_EFFECT)
    end
end```

**Comment by AlphaKretin** [comment]
Doing creation and sabotage

**Comment by EerieCode** [comment]
I'm preparing an utility for the discard replacement of the WC Continuous Spells

**Comment by NaimSantos** [comment]
"Outrigger Expand" is missing "also you cannot Special Summon monsters for the rest of this turn, except EARTH Machine monsters." in its script

**Comment by AlphaKretin** [comment]
With the discard issue out of the way I guess I'll take another crack at Hyne

**Comment by AlphaKretin** [comment]
Doing WC Draping

**Comment by AlphaKretin** [comment]
Gonna do masterpiece

**Comment by AlphaKretin** [comment]
Incidental reminder for posterity (and testing), we also got some cards not from DBIC, including Ankuriboh in the VJMP folder and a vanilla.

**Comment by NaimSantos** [comment]
Added unfished version of Witchcraft Bystreet. Needs the discard replacement effect

**Comment by EerieCode** [comment]
> Added unfished version of Witchcraft Bystreet. Needs the discard replacement effect

I've added that effect. The use of the number instead of id is intentional, it's the one used in the utility.

**Comment by NaimSantos** [comment]
All cards revealed are now finished

**Comment by AlphaKretin** [comment]
Doing Drag Shovel

**Comment by AlphaKretin** [comment]
aaaand trencher
