### ISSUE TITLE
Test for DBIC cards - 12 Feb

### ISSUE THREAD

**Issue by NaimSantos** [EerieCode/Percy-Alpha-Testing#85]
Check if you tested the card. Fix bugs and upload the puzzle to the repository. Comment if there is anything you don't know and/or cannot fix.

- [x] 100412012 - Outrigger Expand
- [x] 100412014 - Witchcraft Potorie 
- [x] 100412015 - Witchcraft Pittole
- [x] 100412017 - Witchcraft Edel
- [x] 100412018 - Witchcraft Heine
- [x] 100412020 - Witchcraft Creation
- [x] 100412021 - Witchcraft Sabotage
- [x] 100412022 - Witchcraft Collaboration
- [x] 100412023 - Witchcraft Draping
- [x] 100412024 - Witchcraft Bystreet
- [x] 100412025 - Witchcraft Scroll
- [ ] 100412026 - Witchcraft Masterpiece

**Comment by NaimSantos** [comment]
Witchcraft Masterpiece: can be activated if you dont have a valid target in the deck. Also, the GY effect banishes 1 less card than what you should. The effect says "equals the number of Spells banished"

**Comment by AlphaKretin** [comment]
Masterpiece was fixed and the cards are now online
