### ISSUE TITLE
VJump Feb 2019 [Scripts]

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#86]
##  Structure Deck R Lord of Magician - 100308XXX
- [x] 100308002 - Empress of Endymion - エンプレス・オブ・エンディミオン
- [x] 100308003 - Magister of Endymion - マギステル・オブ・エンディミオン
- [x] 100308004 - Servant of Endymion - サーヴァント・オブ・エンディミオン
- [x] 100308022 - Spell Power Control - 魔力統轄
- [x] 100308023 - Endimyon Lab - 魔法都市の実験施設
- [x] 100308041 - Guidance of Spell Salvation - 救魔の標
## Starter Deck 2019 - 100319XXX
- [x] 100319041 - Decode Talker Extend - デコード・トーカー・エクステンド
- [x] 100319042 - Trackblack - トラックブラック

**Comment by AlphaKretin** [comment]
Aht's already doing Salvation, I'll do uh. Condensation I guess

**Comment by that-hatter** [comment]
I want all the rest. Lol

**Comment by AlphaKretin** [comment]
It doesn't work that way :V

**Comment by that-hatter** [comment]
Taking Empress

**Comment by AlphaKretin** [comment]
I'll do Lab

**Comment by AlphaKretin** [comment]
Btw, the setcode for Endimyon should be 0x229. Since all the Pendulums are so similar, I'll wait for you to do Empress, then pick whichever one of the remaining you want and I'll take the other.

**Comment by AlphaKretin** [comment]
Eerie has dibs on Magister. I've just about run out of things to do while waiting on Empress, so I'll go ahead and do Servant

**Comment by EerieCode** [comment]
I can do Magister, but it will take a while, I need to reach a computer first

**Comment by that-hatter** [comment]
Empess done

**Comment by AlphaKretin** [comment]
Make a PR here with it

**Comment by AlphaKretin** [comment]
I guess I'll do Extend
