### ISSUE TITLE
[Scripts] - VJump March 2019

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#90]
## Rising Rampage Wave 2 101009XXX
Skyforce = 0x22d
- [x] 101009012 - Skyforce Dragon Adara
- [x] 101009013 - Skyforce Dragon Shutana
- [x] 101009014 - Skyforce Dragon Manila
- [x] 101009015 - Skyforce Dragon Nahata
- [x] 101009016 - Skyforce Dragon Vishuta
- [x] 101009043 - Skyforce Monk
- [x] 101009044 - Skyforce Dragoness
- [x] 101009045 - Skyforce Kishin
- [x] 101009058 -  Skyforce Unbreakable Ground
- [x] 101009059 - Hollow Dragon Ring
- [x] 101009072 - Skyforce Unrivaled Fist

**Comment by AlphaKretin** [comment]
I'll do Flip Frozen

**Comment by AndreOliveiraMendes** [comment]
i'll do cynet cascade

**Comment by AlphaKretin** [comment]
I'll do Threshold Borg

**Comment by AlphaKretin** [comment]
I'll do Rebuildeer

**Comment by EerieCode** [comment]
I'm doing eXcharge.

**Comment by AlphaKretin** [comment]
I'll clean up the backrow

**Comment by AlphaKretin** [comment]
I'll do Cross Debug

**Comment by AlphaKretin** [comment]
I'll clean up the Marincess stuff, I think it's all close enough to be done as a batch

**Comment by EerieCode** [comment]
I'll do the LINK-1 and LINK-2 Marincesses then

**Comment by EerieCode** [comment]
I'll try to do the Field. Maybe the Normal Spell too, if possible.

**Comment by AlphaKretin** [comment]
I'll start doing main decks from the top

**Comment by that-hatter** [comment]
I'm having the counter trap then.

**Comment by NaimSantos** [comment]
i'll do Skyforce Dragon - Manira

**Comment by AlphaKretin** [comment]
I've gotta go now so I'll have to drop out

**Comment by that-hatter** [comment]
On to Shutana
