### ISSUE TITLE
April 2019... Saikyo Jump??? [Scripts]

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#94]
## Yosenju (RIRA - 101009XXX)
https://yu-gi-oh.jp/index.php?page=details&id=534
- [x] 101009009 - Yosenju Saburoukaze - 妖仙獣 侍郎風 **[TESTED]**
- [x] 101009010 - Yosenju Izunamuchi - 妖仙獣 飯綱鞭  **[TESTED]**
- [x] 101009011 - Mayosenju Hitotsumenomuraji - 魔妖仙獣 独眼群主 **[TESTED]**
- [x] 101009057 - Yosenju Wind Ritual - 妖仙獣の風祀り **[TESTED]**
Note: Apparently where Wind Ritual returns "monster cards" it includes both monsters and pendulums.

## Fortune Lady (RIRA - 101009XXX)
https://yu-gi-oh.jp/index.php?page=details&&id=535
- [x] 101009008 - Fortune Lady Past - フォーチュンレディ・パスティー
- [x] 101009038 - Fortune Lady Ever - フォーチュンレディ・エヴァリー
- [x] 101009056 - Fortune Lady Calling - フォーチュンレディ・コーリング
- [x] 101009070 - Fortune Lady Rewind - フォーチュンレディ・リワインド

**Comment by AlphaKretin** [comment]
I'm going to tentatively start scripting Saburo, hopefully reliable translations bear out what I've already seen.

**Comment by AlphaKretin** [comment]
Doing Izuna next

**Comment by AlphaKretin** [comment]
CC is doing Ever, I guess I'll do Past

**Comment by AlphaKretin** [comment]
Past needs spirit elim but I'll move on for now, doing Calling

**Comment by that-hatter** [comment]
Taking Rewind

**Comment by NaimSantos** [comment]
I'll take Yosenju Wind Ritual

**Comment by NaimSantos** [comment]
Taking Mayosenju Hitotsumenomuraji
