### ISSUE TITLE
VJump April and RIRA Leaks [Scripts]

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#96]
## RIRA VJump - 1010090XX
"Simorgh" is setcode 0x22e
- [x] 101009017 - Simorgh, Bird of Beginnings - 雛神鳥シムルグ
- [x] 101009018 - Simorgh, Bird of Summoning - 招神鳥シムルグ
- [x] 101009019 - Simorgh, Bird of Endings - 死神鳥シムルグ
- [x] 101009020 - Simorgh, Bird of Protection - 護神鳥シムルグ
- [x] 101009021 - Simorgh, Lord of the Storm - 烈風の覇者シムルグ
- [x] 101009022 - Darkness Simorgh - ダークネス・シムルグ
- [x] 101009060 - Elborz, Sacred Peak of Simorgh - 神鳥の霊峰エルブルズ
- [x] 101009061 - Simorgh Arrival - 神鳥の来寇
- [x] 101009062 - Simorgh Rejection - 神鳥の排撃
- [x] 101009073 - Simorgh Storms Forth - 神鳥の烈戦

## RIRA Leaks - 1010090XX
- [x] 101009006 - Dinowrestler Martial Anklyo - ダイナレスラー・マーシャルアンキロ
- [x] 101009007 - Dinowrestler Rambrachio - ダイナレスラー・ラアムブラキオ
- [x] 101009026 - Storm Dragon - ランリュウ
- [x] 101009027 - A-vida, the Dual World Crafter - 双星神a-vida
- [x] 101009030 - Cataclysmic Bellowing Colder - 満天禍コルドー
- [x] 101009031 - Voltester - ボルテスター
- [x] 101009035 - Reversible Beetle - リバーシブル・ビートル
- [x] 101009036 - Magistry Ritualist - メギストリーの儀術師
- [x] 101009037 - Magical Scales of Libra - ライブラの魔法秤
- [x] 101009050 - Miss Cape Barber - ミス・ケープ・バーバ
- [x] 101009054 - Fury of Fire - フューリー・オブ・ファイア
- [x] 101009063 - Extreme Nova Burst - 極超辰醒
- [x] 101009064 - Psychic Implosion - 才呼粉身
- [x] 101009065 - Obstructive Curtain - 遮攻カーテン
- [x] 101009066 - Sextet Summon - セクステット・サモン
- [x] 101009079 - Magicite of Spell Salvation - 救魔の奇石
- [x] 101009080 - This Match Is A Draw - 泥仕合

## CP19 VJump (Vision HERO) - 1002480XX
- [x] 100248001 - Ipiria - イピリア
- [x] 100248005 - Vision HERO Minimum Ray - Ｖ・ＨＥＲＯミニマム・レイ
- [x] 100248006 - Vision HERO Multiply Guy - Ｖ・ＨＥＲＯマルティプリ・ガイ
- [x] 100248008 - Vision HERO Poisoner -  Ｖ・ＨＥＲＯポイズナー
- [x] 100248009 - Vision HERO Gravito - Ｖ・ＨＥＲＯグラビート
- [x] 100248010 - Vision HERO Faris -  Ｖ・ＨＥＲＯファリス
- [x] 100248011 - Vision Release - 幻影解放
- [x] 100248012 - Vision Fusion - 幻影融合
- [x] 100248013 - Apparition - 出幻

## CP19 VJump (Fortune Fairy) - 1002480XX
- [x] 100248018 - Fortune Fairy En - 占い魔女 エンちゃん
- [x] 100248019 - Fortune Fairy Hu - 占い魔女 フウちゃん
- [x] 100248020 - Fortune Fairy Swee - 占い魔女 スィーちゃん
- [x] 100248021 - Fortune Fairy Ann - 占い魔女 アンちゃん
- [x] 100248022 - Fortune Fairy Chee - 占い魔女 チーちゃん
- [x] 100248023 - Unacceptable Result - 受け入れがたい結果
- [x] 100248024 - Miracle Stone - 開運ミラクルストーン
- [x] 100248025 - Luck Loan - 幸運の前借り

## CP19 VJump (idk?)
- [x] 100203029 - Luster Liger -
- [x] 100249001 - Progleo - 

## DP22 VJump (Yami Bakura) - 1004220XX
- [x] 100422001 - Curse Necrofear - カース・ネクロフィア
- [x] 100422002 - Dark Spirit of the Denial - 抹殺の邪悪霊
- [x] 100422003 - Dark Spirit of the Malice - 怨念の邪悪霊
- [x] 100422004 - Dark Occultism - ダーク・オカルティズム
- [x] 100422005 - Death Sentence - 死の宣告

**Comment by AlphaKretin** [comment]
I'm already in the middle of Lord of Gales

**Comment by larry126** [comment]
Working on Calling

**Comment by ahtelel** [comment]
Doing 9021, will pull out if there will be classwork in which case I'll notify

**Comment by ahtelel** [comment]
Doing Darkness Simorgh

**Comment by AlphaKretin** [comment]
doing death birb (endings)

**Comment by that-hatter** [comment]
Doing Coming (I assume it's Arrival?)

**Comment by AlphaKretin** [comment]
probably, doublecheck names against org

**Comment by EerieCode** [comment]
I'll do the field

**Comment by larry126** [comment]
I'll do protection

**Comment by AlphaKretin** [comment]
i'll do beginnings then, get the birds out of the way

**Comment by larry126** [comment]
Starting Repelling Strike of Simorgh

**Comment by AlphaKretin** [comment]
aht's doing Darkness, Eerie's doing the field, Hatter's doing Arrival, Larry's doing Rejection, so I'll do Storms Forth

**Comment by AlphaKretin** [comment]
I'll get the petit dragon out of the way while we wait for the rest of the leaks to drop

**Comment by AlphaKretin** [comment]
Dibs on Twin Star God - a-vida (not listed as unknown number)

**Comment by EerieCode** [comment]
Dibs on Sextet Summon, maybe the beetle too

**Comment by AlphaKretin** [comment]
I'm going to clean up the issue and then focus on other things, I'll resume scripting later tonight if stuff's free. Remember to save stuff for Eerie!

**Comment by AndreOliveiraMendes** [comment]
i think i'll do ultra awakening if no one doing

**Comment by AndreOliveiraMendes** [comment]
i'll do draw game

**Comment by that-hatter** [comment]
Taking Scales of Libra

**Comment by EerieCode** [comment]
I'll do the Magicite

**Comment by EerieCode** [comment]
I'll also do Colder. It's mostly C&P, but it has to be done, I guess...

**Comment by AlphaKretin** [comment]
Hey, no shame. I did Storm Dragon, after all. :V

**Comment by that-hatter** [comment]
Psycho Clone

**Comment by that-hatter** [comment]
Miss Cape Barber

**Comment by that-hatter** [comment]
Magistry Ritualist

**Comment by AlphaKretin** [comment]
I've got an idea for Voltester I wanna try out, if no one minds I'll claim that for after locals

**Comment by AlphaKretin** [comment]
Note that the Manga V HEROes seem to be pretty close, so you can use their scripts as starting points. Doing Mini Ray

**Comment by AlphaKretin** [comment]
On to multi guy

**Comment by AlphaKretin** [comment]
Now poisoner

**Comment by AlphaKretin** [comment]
Larry would prefer to take the V HEROes, and Eerie has dibs on the Fortune Fairy spells

**Comment by AlphaKretin** [comment]
Doing En

**Comment by AlphaKretin** [comment]
Hu now

**Comment by AlphaKretin** [comment]
Swee now

**Comment by AlphaKretin** [comment]
Ann now

**Comment by AlphaKretin** [comment]
And finally Chee

**Comment by AlphaKretin** [comment]
Eerie has dibs on Curse Necrofear, Larry on Occult Occultism and Death Sentence

**Comment by that-hatter** [comment]
I'm taking Denial and Malice. They seem similar enough.
