### ISSUE TITLE
VJump April and RIRA Leaks [Tests]

### ISSUE THREAD

**Issue by larry126** [EerieCode/Percy-Alpha-Testing#97]
Check the cards in this issue that you have tested and made necessary fixes (if any) to.
## RIRA VJump
- [x] 101009017 - Simorgh, Bird of Beginnings - 雛神鳥シムルグ
- [x] 101009018 - Simorgh, Bird of Summoning - 招神鳥シムルグ
- [x] 101009019 - Simorgh, Bird of Endings - 死神鳥シムルグ
- [x] 101009020 - Simorgh, Bird of Protection - 護神鳥シムルグ
- [x] 101009021 - Simorgh, Lord of the Storm - 烈風の覇者シムルグ
- [x] 101009022 - Darkness Simorgh - ダークネス・シムルグ
- [x] 101009060 - Elborz, Sacred Peak of Simorgh - 神鳥の霊峰エルブルズ
- [x] 101009061 - Simorgh Arrival - 神鳥の来寇
- [x] 101009062 - Simorgh Rejection - 神鳥の排撃
- [x] 101009073 - Simorgh Storms Forth - 神鳥の烈戦

## RIRA Leaks
- [x] 101009006 - Dinowrestler Martial Anklyo - ダイナレスラー・マーシャルアンキロ
- [x] 101009007 - Dinowrestler Rambrachio - ダイナレスラー・ラアムブラキオ
- [x] 101009026 - Storm Dragon - ランリュウ
- [x] 101009027 - A-vida, the Dual World Crafter - 双星神a-vida
- [x] 101009030 - Cataclysmic Bellowing Colder - 満天禍コルドー
- [x] 101009031 - Voltester - ボルテスター
- [x] 101009035 - Reversible Beetle - リバーシブル・ビートル
- [x] 101009036 - Magistry Ritualist - メギストリーの儀術師
- [x] 101009037 - Magical Scales of Libra - ライブラの魔法秤
- [x] 101009047 - Link Mail Archfiend
- [x] 101009050 - Miss Cape Barber - ミス・ケープ・バーバ
- [x] 101009054 - Fury of Fire - フューリー・オブ・ファイア
- [x] 101009063 - Extreme Nova Burst - 極超辰醒
- [x] 101009064 - Psychic Implosion - 才呼粉身
- [x] 101009065 - Obstructive Curtain - 遮攻カーテン
- [x] 101009066 - Sextet Summon - セクステット・サモン
- [x] 101009079 - Magicite of Spell Salvation - 救魔の奇石
- [x] 101009080 - This Match Is A Draw - 泥仕合

**Comment by AlphaKretin** [comment]
Leaving Sextet Summon alone for now, as noted in commit description hangs the game likely due to excessive/infinite recursion. Gonna be a tricky one to figure out.

**Comment by EerieCode** [comment]
Sextet works now, but it's still not 100% complete. We'll need a better check that can handle Pendulum Hybrids
