### ISSUE TITLE
VJump... May??? [Scripts]

### ISSUE THREAD

**Issue by AlphaKretin** [EerieCode/Percy-Alpha-Testing#98]
## Structure Deck: Revolver and Extra Deck Enhancement Pack - 100336XXX
- [x] 100336051 - Borreload Furious Dragon - ヴァレルロード・Ｆ・ドラゴン
- [x] 100336052 - Sawnborrel Dragon - ソーンヴァレル・ドラゴン
- [x] 100336024 - Rapid Trigger - ラピッド・トリガー
- [x] 100336041 - Topologic Zerovoros - トポロジック・ゼロヴォロス

## Duelist Pack: Legend Duelist 5 - 1004220XX
- [x] 100422012 - Evil HERO Malicious Bane - Ｅ－ＨＥＲＯ マリシャス・ベイン
- [x] 100422023 - Earthbound Super Priest - 地縛超神官
- [x] 100422034 - Gimmick Puppet Gigantes Doll - ギミック・パペット－ギガンテス・ドール
- [x] 100422045 - Predaplant Triphyovertum - 捕食植物トリフィオヴェルトゥム

## Chaos Impact - 101010XXX
- [x] 101010037 - Firewall Dragon Darkfluid
- [x] 101010014 - Starliege Dragon Seyfert - 輝光竜セイファート
- [x] 101010047 - Galaxy Satellite Dragon - 銀河衛竜

## Collector's Pack: Duelist of Revolution Version - 1002480XX
 - [x] 100248027 - T.G. Drill Fish - ＴＧ ドリル・フィッシュ
 - [x] 100248028 - T.G. Metal Skeleton - ＴＧ メタル・スケルトン
 - [x] 100248029 - Sonic Stun (Battle Stun Sonic) - バトル・スタン・ソニック

**Comment by larry126** [comment]
Dibs on Topologic Zerovolos

**Comment by AlphaKretin** [comment]
I guess I'll do BFD

**Comment by larry126** [comment]
Topologic Zerovolos undoable sadly, FCD issue

**Comment by larry126** [comment]
Dibs on fusion instead

**Comment by AlphaKretin** [comment]
Doing a prototype (skipping the tricky effect) of Zerovoros, with Larry's blessing

**Comment by AlphaKretin** [comment]
OK, we think we have a working Zerovoros. I've tested the basic situation for its problematic effect, but I'm not aware of any edge cases and I haven't got around to testing its other effects.

**Comment by AlphaKretin** [comment]
I have dibs on Earthbound Rex Goodwin, Larry on the HERO

**Comment by AlphaKretin** [comment]
Working on Gigantes Doll

**Comment by AlphaKretin** [comment]
Eerie has dibs on Darkfluid

**Comment by AlphaKretin** [comment]
I dibs Galaxy Satellite Dragon
